export const IATA_TO_CITY: Record<string, string> = {
  "AAC": "Al Arish",
  "AAE": "Annaba",
  "AAG": "Arapoti",
  "AAL": "Aalborg",
  "AAN": "Al Ain",
  "AAQ": "Anapa",
  "AAT": "Altay",
  "AAY": "Al Ghaydah",
  "ABA": "Abakan",
  "ABD": "Abadan",
  "ABE": "Allentown",
  "ABI": "Abilene",
  "ABJ": "Abidjan",
  "ABK": "Kabri Dar",
  "ABL": "Ambler",
  "ABM": "Bamaga",
  "ABQ": "Albuquerque",
  "ABR": "Aberdeen",
  "ABS": "Abu Simbel",
  "ABT": "Al-Baha",
  "ABV": "Abuja",
  "ABX": "Albury",
  "ACA": "Acapulco",
  "ACC": "Accra",
  "ACE": "Lanzarote",
  "ACH": "Altenrhein",
  "ACI": "Alderney",
  "ACK": "Nantucket",
  "ACT": "Waco",
  "ACV": "Arcata",
  "ADA": "Adana",
  "ADB": "Izmir",
  "ADD": "Addis Ababa",
  "ADE": "Aden",
  "ADK": "Adak Island",
  "ADL": "Adelaide",
  "ADQ": "Kodiak",
  "ADU": "Ardabil",
  "ADZ": "San Andres Island",
  "AEO": "Aioun El Atrouss",
  "AEP": "Buenos Aires",
  "AER": "Adler/sochi",
  "AES": "Aalesund",
  "AET": "Allakaket",
  "AEX": "Alexandria",
  "AEY": "Akureyri",
  "AFA": "San Rafael",
  "AFT": "Afutara",
  "AGA": "Agadir",
  "AGB": "Augsburg/Munich",
  "AGD": "Anggi",
  "AGE": "Wangerooge",
  "AGF": "Agen",
  "AGH": "Argelholm/Helsingborg",
  "AGJ": "Aguni",
  "AGL": "Wanigela",
  "AGN": "Angoon",
  "AGP": "Malaga",
  "AGR": "Agra",
  "AGS": "Augusta",
  "AGT": "Ciudad Del Este",
  "AGU": "Aguascalientes",
  "AGV": "Acarigua",
  "AHB": "Abha",
  "AHN": "Athens",
  "AHO": "Alghero",
  "AHU": "Al Hoceima",
  "AIA": "Alliance",
  "AIC": "Airok",
  "AIM": "Ailuk Island",
  "AIN": "Wainwright",
  "AIT": "Aitutaki",
  "AIU": "Atiu Island",
  "AIY": "Atlantic City",
  "AJA": "Ajaccio",
  "AJF": "Jouf",
  "AJI": "Agri",
  "AJL": "Aizawl",
  "AJR": "Arvidsjaur",
  "AJU": "Araca",
  "AKA": "Ankang",
  "AKB": "Atka",
  "AKF": "Kufrah",
  "AKI": "Akiak",
  "AKJ": "Asahikawa",
  "AKL": "Auckland",
  "AKN": "King Salmon",
  "AKP": "Anaktueuk",
  "AKS": "Auki",
  "AKU": "Aksu",
  "AKV": "Akulivik",
  "AKX": "Almaty",
  "AKY": "Sittwe",
  "ALB": "Albany",
  "ALC": "Alicante",
  "ALF": "Alta",
  "ALG": "Algiers",
  "ALJ": "Alexander Bay",
  "ALM": "Alamogordo",
  "ALO": "Waterloo",
  "ALP": "Aleppo",
  "ALS": "Alamosa",
  "ALW": "Walla Walla",
  "AMA": "Amarillo",
  "AMD": "Ahmedabad",
  "AMH": "Arba Mintch",
  "AMI": "Mataram",
  "AMM": "Amman",
  "AMO": "Mao",
  "AMQ": "Ambon",
  "AMS": "Amsterdam",
  "AMV": "Amderma",
  "AMY": "Ambatomainty",
  "ANC": "Anchorage",
  "ANE": "Angers",
  "ANF": "Antofagasta",
  "ANG": "Angouleme",
  "ANI": "Aniak",
  "ANM": "Antalaha",
  "ANR": "Antwerp",
  "ANU": "Antigua",
  "ANV": "Anvik",
  "ANX": "Andenes",
  "AOI": "Ancona",
  "AOJ": "Aomori",
  "AOK": "Karpathos",
  "AOL": "Paso De Los Libres",
  "AOO": "Altoona",
  "AOR": "Alorsetar",
  "AOT": "Aosta",
  "APF": "Naples",
  "APL": "Nampula",
  "APN": "Alpena",
  "APO": "Apartado",
  "APW": "Apia",
  "AQG": "Anging",
  "AQI": "Qaisumah",
  "AQJ": "Aqaba",
  "AQP": "Arequipa",
  "ARC": "Arctic Village",
  "ARD": "Alor Island",
  "ARH": "Arkangelsk",
  "ARI": "Arica",
  "ARK": "Arusha",
  "ARM": "Armidale",
  "ARN": "Stockholm",
  "ARP": "Aragip",
  "ARR": "Alto Rio Senguerr",
  "ART": "Watertown",
  "ARU": "Aracatuba",
  "ARW": "Arad",
  "ASB": "Ashgabat",
  "ASD": "Andros",
  "ASE": "Aspen",
  "ASF": "Astrakhan",
  "ASJ": "Amami O Shima",
  "ASM": "Asmara",
  "ASO": "Asosa",
  "ASP": "Alice Springs",
  "ASR": "Kayseri",
  "ASU": "Asuncion",
  "ASV": "Amboseli",
  "ASW": "Aswan",
  "ATD": "Atoifi",
  "ATK": "Atqasuk",
  "ATL": "Atlanta",
  "ATM": "Altamira",
  "ATN": "Namatana",
  "ATQ": "Amritsar",
  "ATW": "Appleton",
  "ATZ": "Assiut",
  "AUA": "Aruba",
  "AUC": "Arauca",
  "AUH": "Abu Dhabi",
  "AUK": "Alakanuk",
  "AUL": "Aur Island",
  "AUP": "Agaun",
  "AUQ": "Atuona",
  "AUR": "Aurillac",
  "AUS": "Austin",
  "AUU": "Aurukun",
  "AUX": "Araguaina",
  "AUY": "Aneityum",
  "AVI": "Ciego De Avila",
  "AVL": "Asheville",
  "AVN": "Avignon",
  "AVP": "Scranton",
  "AWD": "Aniwa",
  "AWZ": "Ahwaz",
  "AXA": "Anguilla",
  "AXD": "Alexandroupolis",
  "AXK": "Ataq",
  "AXM": "Armenia",
  "AXP": "Spring Point",
  "AXT": "Akita",
  "AYQ": "Ayers Rock",
  "AYT": "Antalya",
  "AYW": "Ayawaki",
  "AZB": "Amazon Bay",
  "AZD": "Yazd",
  "AZN": "Andizhan",
  "AZO": "Kalamazoo",
  "AZR": "Adrar",
  "BAH": "Bahrain",
  "BAK": "Baku",
  "BAL": "Batman",
  "BAQ": "Barranquilla",
  "BAS": "Balalae",
  "BAU": "Bauru",
  "BAV": "Baotou",
  "BAX": "Barnaul",
  "BAY": "Baia Mare",
  "BBA": "Balmaceda",
  "BBI": "Bhubaneswar",
  "BBK": "Kasane",
  "BBM": "Battambang",
  "BBN": "Bario",
  "BBO": "Berbera",
  "BBU": "Bucharest",
  "BCA": "Baracoa",
  "BCD": "Bacolod",
  "BCI": "Barcaldine",
  "BCL": "Barra Colorado",
  "BCN": "Barcelona",
  "BCO": "Jinka",
  "BCQ": "Brack",
  "BDA": "Bermuda",
  "BDB": "Bundaberg",
  "BDD": "Badu Island",
  "BDH": "Bandar Lengeh",
  "BDJ": "Banjarmasin",
  "BDL": "Hartford",
  "BDO": "Bandung",
  "BDP": "Bhadrapur",
  "BDQ": "Vadodara",
  "BDS": "Brindisi",
  "BDU": "Bardufoss",
  "BEB": "Benbecula",
  "BED": "Bedford",
  "BEG": "Belgrade",
  "BEH": "Benton Harbor",
  "BEI": "Beica",
  "BEJ": "Berau",
  "BEL": "Belem",
  "BEN": "Benghazi",
  "BEO": "Newcastle",
  "BER": "Berlin",
  "BES": "Brest",
  "BET": "Bethel",
  "BEU": "Bedourie",
  "BEW": "Beira",
  "BEY": "Beirut",
  "BFD": "Bradford",
  "BFF": "Scottsbluff",
  "BFL": "Bakersfield",
  "BFN": "Bloemfontein",
  "BFQ": "Bahia Pinas",
  "BFS": "Belfast",
  "BFV": "Buri Ram",
  "BGA": "Bucaramanga",
  "BGF": "Banqui",
  "BGI": "Barbados",
  "BGM": "Binghamton",
  "BGO": "Bergen",
  "BGR": "Bangor",
  "BHB": "Bar Harbour",
  "BHE": "Blenheim",
  "BHG": "Brus Laguna",
  "BHH": "Bisha",
  "BHI": "Bahia Blanca",
  "BHJ": "Bhuj",
  "BHK": "Bukhara",
  "BHM": "Birmingham",
  "BHO": "Bhopal",
  "BHQ": "Broken Hill",
  "BHR": "Bharatpur",
  "BHS": "Bathurst",
  "BHU": "Bhavnagar",
  "BHV": "Bahawalpur",
  "BHY": "Beihai",
  "BIA": "Bastia",
  "BID": "Block Island",
  "BII": "Bikini Atoll",
  "BIK": "Biak",
  "BIL": "Billings",
  "BIM": "Bimini",
  "BIO": "Bilbao",
  "BIQ": "Biarritz",
  "BIR": "Biratragar",
  "BIS": "Bismarck",
  "BJA": "Bejaia",
  "BJB": "Bojnord",
  "BJF": "Batsfijord",
  "BJI": "Bemidji",
  "BJL": "Banjul",
  "BJM": "Bujumbura",
  "BJR": "Baharpar",
  "BJV": "Bodrum",
  "BJX": "Guanajuato",
  "BJZ": "Badajcz",
  "BKC": "Buckland",
  "BKI": "Kota Kinabalu",
  "BKK": "Bangkok",
  "BKO": "Bamako",
  "BKQ": "Blackall",
  "BKS": "Bengkulu",
  "BKW": "Beckley",
  "BKX": "Brookings",
  "BKZ": "Bukoba",
  "BLE": "Borlange",
  "BLF": "Bluefield",
  "BLG": "Belaga",
  "BLI": "Bellingham",
  "BLJ": "Batna",
  "BLK": "Blackpool",
  "BLL": "Billund",
  "BLR": "Bangalore",
  "BLT": "Blackwater",
  "BLV": "Belleville",
  "BLZ": "Blantyre",
  "BMD": "Belo",
  "BME": "Broome",
  "BMI": "Bloomington",
  "BMK": "Borkum",
  "BMO": "Bhamo",
  "BMP": "Brampton Island",
  "BMU": "Bima",
  "BMV": "Banmethuot",
  "BMY": "Belep Island",
  "BNA": "Nashville",
  "BND": "Bandar Abbas",
  "BNE": "Brisbane",
  "BNJ": "Bonn",
  "BNK": "Ballina",
  "BNN": "Bronnoysund",
  "BNP": "Bannu",
  "BNS": "Barinas",
  "BNX": "Banja Luka",
  "BNY": "Bellona",
  "BOA": "Boma",
  "BOB": "Bora Bora",
  "BOC": "Bocas Del Toro",
  "BOD": "Bordeaux",
  "BOG": "Bogota",
  "BOH": "Bournemouth",
  "BOI": "Boise",
  "BOJ": "Bourgas",
  "BOM": "Bombay",
  "BON": "Bonaire",
  "BOO": "Bodo",
  "BOS": "Boston",
  "BOV": "Boang",
  "BOX": "Borroloola",
  "BPF": "Batuna",
  "BPN": "Balikpapan",
  "BPS": "Porto Seguro",
  "BPT": "Beaumont/Port Arthur",
  "BPX": "Bangda",
  "BPY": "Besalampy",
  "BQK": "Brunswick",
  "BQL": "Boulia",
  "BQN": "Aguadilla",
  "BQS": "Blagoveschensk",
  "BRA": "Barreiras",
  "BRC": "San Carlos",
  "BRD": "Brainerd",
  "BRE": "Bremen",
  "BRI": "Bari",
  "BRK": "Bourke",
  "BRL": "Burlington",
  "BRM": "Barquisimeto",
  "BRN": "Berne",
  "BRO": "Brownsville",
  "BRQ": "Brno",
  "BRR": "Barra",
  "BRT": "Bathurst Island",
  "BRU": "Brussels",
  "BRW": "Barrow",
  "BSA": "Bossaro",
  "BSB": "Brasilia",
  "BSC": "Bahia Solano",
  "BSD": "Baoshan",
  "BSK": "Biskra",
  "BSL": "Basel",
  "BSO": "Basco",
  "BTH": "Batam",
  "BTI": "Barter Island",
  "BTJ": "Banda Aceh",
  "BTK": "Bratsk",
  "BTM": "Butte",
  "BTR": "Baton Rouge",
  "BTS": "Bratislava",
  "BTT": "Bettles",
  "BTU": "Bintulu",
  "BUA": "Buka",
  "BUC": "Burketown",
  "BUD": "Budapest",
  "BUF": "Buffalo",
  "BUI": "Bokondini",
  "BUO": "Burao",
  "BUQ": "Bulawayo",
  "BUR": "Burbank",
  "BUS": "Batumi",
  "BUZ": "Bashehr",
  "BVB": "Boavista",
  "BVC": "Boa Vista",
  "BVE": "Brive-La-Gaillarde",
  "BVG": "Berlevag",
  "BVH": "Vilhena",
  "BVI": "Birdsville",
  "BWA": "Bhairawa",
  "BWD": "Brawnwood",
  "BWE": "Braunschweig",
  "BWG": "Bowling Green",
  "BWI": "Baltimore",
  "BWK": "Bol",
  "BWN": "Bandar Seri Begawan",
  "BWQ": "Brewarrina",
  "BWT": "Burnie",
  "BXB": "Babo",
  "BXD": "Bade",
  "BXM": "Batom",
  "BXR": "Bam",
  "BXU": "Butuan",
  "BXZ": "Bunsil",
  "BYA": "Boundary",
  "BYM": "Bayamo",
  "BYU": "Bayreuth",
  "BZE": "Belize City",
  "BZG": "Bydgoszcz",
  "BZI": "Balikesir",
  "BZL": "Barisal",
  "BZN": "Bozeman",
  "BZO": "Bolzano",
  "BZR": "Beziers",
  "BZV": "Brazzaville",
  "CAC": "Cascavel",
  "CAG": "Cagliari",
  "CAI": "Cairo",
  "CAK": "Canton/Akron",
  "CAL": "Campbeltown",
  "CAN": "Guangzhou",
  "CAP": "Cap Haitien",
  "CAQ": "Caucasia",
  "CAS": "Canaima",
  "CAW": "Campos",
  "CAY": "Cayenne",
  "CAZ": "Cobar",
  "CBB": "Cochabamba",
  "CBE": "Cumberland",
  "CBG": "Cambridge",
  "CBH": "Bechar",
  "CBL": "Ciudad Bolivar",
  "CBO": "Cotabato",
  "CBQ": "Calabar",
  "CBR": "Canberra",
  "CCC": "Cayo Coco",
  "CCF": "Carcassonne",
  "CCJ": "Kozhikode",
  "CCM": "Criciuma",
  "CCP": "Concepcion",
  "CCR": "Concord",
  "CCS": "Caracas",
  "CCU": "Calcutta",
  "CCV": "Craig Cove",
  "CDB": "Cold Bay",
  "CDC": "Cedar City",
  "CDG": "Paris",
  "CDR": "Chadron",
  "CDV": "Cordova",
  "CEB": "Cebu",
  "CEC": "Crescent City",
  "CED": "Cedun",
  "CEE": "Cherepovets",
  "CEG": "Chester",
  "CEI": "Chiang Rai",
  "CEK": "Chelybinsk",
  "CEM": "Central",
  "CEN": "Ciudad Obregon",
  "CEQ": "Cannes",
  "CEZ": "Cortez",
  "CFA": "Coffee Point",
  "CFE": "Clermont-Ferrand",
  "CFG": "Cienfuegos",
  "CFN": "Donegal",
  "CFR": "Caen",
  "CFS": "Coffs Harbor",
  "CFU": "Corfu",
  "CGA": "Craig",
  "CGB": "Cuiaba",
  "CGD": "Changde",
  "CGH": "Sao Paulo",
  "CGI": "Cape Girardeau",
  "CGK": "Jakarta",
  "CGO": "Zhengzha",
  "CGP": "Chittagong",
  "CGQ": "Changchun",
  "CGR": "Campo Grande",
  "CGY": "Cagayan De Oro",
  "CHA": "Chattanooga",
  "CHC": "Christchurch",
  "CHG": "Chaoyang",
  "CHO": "Charlottesville",
  "CHP": "Circle Hot Springs",
  "CHQ": "Chania",
  "CHS": "Charleston",
  "CHT": "Chatham Island",
  "CHU": "Chuathbaluk",
  "CHX": "Changuinda",
  "CHY": "Choiseul Bay",
  "CIC": "Chico",
  "CID": "Cedar Rapids",
  "CIF": "Chifeng",
  "CIJ": "Cobija",
  "CIK": "Chalkyitsik",
  "CIP": "Chipata",
  "CIT": "Shimkent",
  "CIU": "Sault Ste Marie",
  "CIW": "Canouan",
  "CIX": "Chicayo",
  "CJA": "Cajamarca",
  "CJB": "Coimbatore",
  "CJC": "Calama",
  "CJJ": "Cheongju",
  "CJL": "Chitral",
  "CJS": "Ciudad Juarez",
  "CJU": "Jeju",
  "CKB": "Clarksburg",
  "CKG": "Chongqing",
  "CKI": "Croker Island",
  "CKO": "Crooked Creek",
  "CKS": "Carajas",
  "CKX": "Chicken",
  "CKY": "Conakry",
  "CLD": "Carlsbad",
  "CLE": "Cleveland",
  "CLJ": "Cluj",
  "CLL": "College Station",
  "CLM": "Port Angeles",
  "CLO": "Cali",
  "CLP": "Clarks Point",
  "CLQ": "Colima",
  "CLT": "Charlotte",
  "CLY": "Calvi",
  "CMA": "Cunnamulla",
  "CMB": "Colombo",
  "CME": "Ciudad Del Carmen",
  "CMF": "Chambery",
  "CMG": "Corumba",
  "CMI": "Champaign/Urbana",
  "CMJ": "Chi Mei",
  "CMK": "Club Makokola",
  "CMN": "Casablanca",
  "CMU": "Kundiawa",
  "CMW": "Camaguey",
  "CMX": "Hancock",
  "CNB": "Coonamble",
  "CNC": "Coconut Island",
  "CND": "Constanta",
  "CNF": "Blo Horizonte",
  "CNJ": "Cloncurry",
  "CNK": "Concordia",
  "CNP": "Neerlerit Inaat",
  "CNQ": "Corrientes",
  "CNS": "Cairns",
  "CNX": "Chiang Mai",
  "CNY": "Moab",
  "COC": "Cotarou",
  "COD": "Cody/Yellowstone",
  "COG": "Condoto",
  "COK": "Cochin",
  "COR": "Cordoba",
  "COS": "Colorado Springs",
  "COU": "Columbia",
  "CPC": "San Martin De Los Andes",
  "CPD": "Coober Pedy",
  "CPE": "Campeche",
  "CPH": "Copenhagen",
  "CPI": "Cape Orford",
  "CPO": "Copiapo",
  "CPQ": "Campinas",
  "CPR": "Casper",
  "CPT": "Cape Town",
  "CPV": "Campina Grande",
  "CRD": "Camodoro",
  "CRI": "Crooked Island",
  "CRP": "Corpus Christi",
  "CRV": "Crotone",
  "CSG": "Columbus",
  "CSI": "Casino",
  "CST": "Castaway",
  "CSY": "Cheboksary",
  "CTA": "Catania",
  "CTC": "Catamarca",
  "CTD": "Chitre",
  "CTG": "Cartagena",
  "CTL": "Charleville",
  "CTM": "Chetumal",
  "CTN": "Cooktown",
  "CTS": "Sapporo",
  "CTU": "Chergdu",
  "CUC": "Cucata",
  "CUE": "Cuenca",
  "CUL": "Culiacan",
  "CUM": "Cumana",
  "CUN": "Cancun",
  "CUP": "Carupani",
  "CUQ": "Coen",
  "CUR": "Curacao",
  "CUU": "Chihuahua",
  "CUW": "Cube Cove",
  "CUZ": "Cusco",
  "CVC": "Cleve",
  "CVG": "Cincinnati",
  "CVJ": "Cuernavaca",
  "CVL": "Cape Vogel",
  "CVM": "Ciudad Victoria",
  "CVN": "Clovis",
  "CVQ": "Carnarvon",
  "CVU": "Corvo Island",
  "CWA": "Stevens Point/Wausau",
  "CWB": "Curitiba",
  "CWL": "Cardiff",
  "CXJ": "Caxias Do Sul",
  "CYB": "Cayman Brac Is",
  "CYF": "Chefornak",
  "CYI": "Chiayi",
  "CYO": "Cayo Largo Del Sur",
  "CYS": "Cheyenne",
  "CZE": "Coro",
  "CZH": "Corozal",
  "CZL": "Constantine",
  "CZM": "Cozumel",
  "CZN": "Chisana",
  "CZS": "Cruzeiro Do Sul",
  "CZX": "Changzhou",
  "DAB": "Daytona Beach",
  "DAC": "Dhaka",
  "DAD": "Da Nang",
  "DAM": "Damascus",
  "DAR": "Dar Es Salaam",
  "DAU": "Daru",
  "DAV": "David",
  "DAX": "Daxian",
  "DAY": "Dayton",
  "DBM": "Debra Marcos",
  "DBO": "Dubbo",
  "DBQ": "Dubuque",
  "DBT": "Debra Tabor",
  "DBV": "Dubrovnik",
  "DCA": "Washington Dc",
  "DCF": "Dominica",
  "DCM": "Castres",
  "DDC": "Dodge City",
  "DDI": "Daydream Is",
  "DDM": "Dodoima",
  "DEA": "Dera Ghazi",
  "DEC": "Decatur",
  "DEL": "Delhi",
  "DEM": "Dembidollo",
  "DEN": "Denver",
  "DER": "Derim",
  "DEZ": "Deirezzor",
  "DFW": "Dallas/Fort Worth",
  "DGA": "Dangriga",
  "DGE": "Mudgee",
  "DGT": "Dumaguete",
  "DHN": "Dothan",
  "DIB": "Dibrugarn",
  "DIE": "Antsiranana",
  "DIJ": "Dijon",
  "DIK": "Dickinson",
  "DIL": "Dili",
  "DIN": "Dien Bien Phu",
  "DIR": "Dire Dawa",
  "DIU": "Div",
  "DIY": "Diyarbakir",
  "DJB": "Jambi. Indonesia",
  "DJE": "Djerba",
  "DJG": "Djanet",
  "DJJ": "Jayapura",
  "DJN": "Delta Junction",
  "DKI": "Dunk Island",
  "DKR": "Dakar",
  "DLA": "Dovala",
  "DLC": "Dalian",
  "DLG": "Dillingham",
  "DLH": "Duluth",
  "DLM": "Dalaman",
  "DLU": "Dali City",
  "DLY": "Dillons Bay",
  "DMD": "Doomadgee",
  "DMM": "Dammam",
  "DMU": "Dimapur",
  "DND": "Dundee",
  "DNH": "Dunhuang",
  "DNK": "Dnepropetrovsk",
  "DNM": "Denham",
  "DNR": "Dinard",
  "DNZ": "Denizli",
  "DOB": "Dobo",
  "DOD": "Dodoma",
  "DOG": "Dongola",
  "DOH": "Doha",
  "DOK": "Donetsk",
  "DOL": "Deauville",
  "DOU": "Dourados",
  "DPL": "Dipolog",
  "DPO": "Devonport",
  "DPS": "Bali",
  "DRB": "Derby",
  "DRG": "Deering",
  "DRH": "Dabra",
  "DRO": "Durango",
  "DRS": "Dresden",
  "DRW": "Darwin",
  "DSE": "Dessie",
  "DSK": "Dera Ismail Khan",
  "DSM": "Des Moines",
  "DTD": "Datadawai",
  "DTM": "Dortmund",
  "DTT": "Detroit",
  "DUB": "Dublin",
  "DUD": "Dunedin",
  "DUJ": "Dubois",
  "DUM": "Dumai",
  "DUQ": "Duncan/Quam",
  "DUR": "Durban",
  "DUS": "Dusseldorf",
  "DUT": "Dutch Harbor",
  "DVO": "Davao",
  "DWB": "Soalala",
  "DXB": "Dubai",
  "DYG": "Dayang",
  "DYR": "Anadyr",
  "DYU": "Dushanbe",
  "DZA": "Dzaoudzi",
  "EAE": "Emae",
  "EAM": "Nejran",
  "EAR": "Kearney",
  "EAS": "San Sebastian",
  "EAT": "Wenatchee",
  "EAU": "Eau Claire",
  "EBA": "Elba Island",
  "EBB": "Entebbe",
  "EBD": "El Obeid",
  "EBJ": "Esbjerg",
  "EBO": "Ebon",
  "EBU": "St. Etienne",
  "ECN": "Ercan",
  "EDA": "Edna Bay",
  "EDI": "Edinburgh",
  "EDL": "Eldoret",
  "EDO": "Edremit",
  "EDR": "Edward River",
  "EEK": "Eek",
  "EEN": "Keene",
  "EFL": "Kefallinia",
  "EGC": "Bergerac",
  "EGE": "Vail",
  "EGL": "Neghelli",
  "EGM": "Sege",
  "EGN": "Geneina",
  "EGO": "Belgorod",
  "EGS": "Egilsstadir",
  "EHL": "El Bolsan",
  "EHM": "Cape Newenham",
  "EIB": "Eisenach",
  "EIN": "Eindhoven",
  "EIS": "Beef Island",
  "EJA": "Barran Cabermeja",
  "EJH": "Wedjh",
  "EKO": "Elko",
  "ELC": "Elcho Island",
  "ELD": "El Dorado",
  "ELE": "El Real",
  "ELF": "El Fasher",
  "ELH": "Eleuthera Island",
  "ELI": "Elim",
  "ELM": "Elmira",
  "ELP": "El Paso",
  "ELQ": "Gassim",
  "ELS": "East London",
  "ELU": "El Oved",
  "ELV": "Elfin Cove",
  "EMA": "Nottingham",
  "EMD": "Emerald",
  "EMK": "Emmonak",
  "EMN": "Nema",
  "EMO": "Emo",
  "EMS": "Embessa",
  "EMX": "El Maiten",
  "ENA": "Kenai",
  "ENE": "Ende",
  "ENF": "Enontekio",
  "ENH": "Enshi",
  "ENT": "Enewetak Island",
  "ENU": "Enugu",
  "EOI": "Eday",
  "EPL": "Epinal",
  "EPR": "Esperance",
  "EPS": "El Portillo/samana",
  "EQS": "Esquel",
  "ERC": "Erzincan",
  "ERF": "Erfurt",
  "ERI": "Erie",
  "ERZ": "Erzurum",
  "ESB": "Ankara",
  "ESC": "Escanaba",
  "ESL": "Elista",
  "ESM": "Esmeraldas",
  "ESR": "El Salvador",
  "ETH": "Elat",
  "ETZ": "Metz/Nancy",
  "EUE": "Eureka",
  "EUG": "Eugene",
  "EUN": "Laayoune",
  "EUX": "St. Eustatius",
  "EVE": "Harstad-Narvik",
  "EVG": "Sveg",
  "EVN": "Yerevan",
  "EVV": "Evansville",
  "EWE": "Ewer",
  "EWI": "Enarotali",
  "EWR": "Newark",
  "EXM": "Exmouth Gulf",
  "EXT": "Eveter",
  "EYL": "Yelimane",
  "EYP": "El Yopal",
  "EYW": "Key West",
  "EZE": "Buenos Aires",
  "EZS": "Elazig",
  "FAE": "Faroe Islands",
  "FAI": "Fairbanks",
  "FAJ": "Fajard",
  "FAO": "Faro",
  "FAR": "Fargo",
  "FAT": "Fresno",
  "FAV": "Fakarava",
  "FBM": "Lumbashi",
  "FCA": "Glacier",
  "FCO": "Rome",
  "FDE": "Forde",
  "FDF": "Fort De France",
  "FDH": "Friedrichshafer",
  "FEG": "Fergana",
  "FEN": "Fernando De Noronha",
  "FEZ": "Fez",
  "FIE": "Fair Isle",
  "FIH": "Kinshasa",
  "FIZ": "Fitzroy Crossing",
  "FJR": "Al-Fujairah",
  "FKB": "Karlsruhe/Badern Baden",
  "FKL": "Franklin",
  "FKQ": "Fak Fak",
  "FKS": "Fukushima",
  "FLA": "Florencia",
  "FLF": "Flensburg",
  "FLG": "Flagstaff",
  "FLL": "Fort Lauderdale",
  "FLN": "Florianopolis",
  "FLR": "Florence",
  "FLW": "Flores Island",
  "FMA": "Formosa",
  "FMO": "Muenster",
  "FNA": "Freetown",
  "FNC": "Funchal",
  "FNI": "Nimes",
  "FNJ": "Pyongyang",
  "FNL": "Fort Collins/Loveland",
  "FNT": "Flint",
  "FOC": "Fuzhou",
  "FOD": "Fort Dodge",
  "FOE": "Topeka",
  "FOG": "Foggia",
  "FOR": "Fortaleza",
  "FPO": "Freeport",
  "FRC": "Franca",
  "FRE": "Fera Island",
  "FRO": "Floro",
  "FRS": "Flores",
  "FRU": "Bishkek",
  "FRW": "Francistown",
  "FSC": "Figari",
  "FSD": "Sioux Falls",
  "FSM": "Fort Smith",
  "FSP": "St Pierre",
  "FTA": "Futuna Island",
  "FTE": "Patagonia",
  "FTU": "Fort Dauphin",
  "FUE": "Fuerteventura",
  "FUG": "Fuyang",
  "FUJ": "Fukue",
  "FUK": "Fukuoka",
  "FUN": "Funafuti Atol",
  "FWA": "Fort Wayne",
  "FYV": "Fayetteville",
  "FZO": "Filton",
  "GAF": "Gafsa",
  "GAJ": "Yamagata",
  "GAN": "Gan Island",
  "GAO": "Guantanamo",
  "GAR": "Garaina",
  "GAU": "Gawahati",
  "GAX": "Gamba",
  "GBE": "Gaborone",
  "GBL": "Goulburn Island",
  "GCC": "Gillette",
  "GCI": "Guernsey",
  "GCK": "Garden City",
  "GCM": "Grand Cayman",
  "GDE": "Gode/Iddidole",
  "GDL": "Guadalajara",
  "GDN": "Gdansk",
  "GDQ": "Gondari",
  "GDT": "Grand Turk Island",
  "GDV": "Glendive",
  "GDX": "Magadan",
  "GDZ": "Gelendzik",
  "GEB": "Gebe",
  "GEG": "Spokane",
  "GEL": "Santo Angelo",
  "GER": "Nueva Gerona",
  "GES": "General Santos",
  "GET": "Geraldton",
  "GEV": "Gallivare",
  "GFF": "Griffith",
  "GFK": "Grand Forks",
  "GFN": "Grafton",
  "GGG": "Gladewater/Kilgore",
  "GGN": "Gagnoa",
  "GGS": "Gobernador Gregores",
  "GGT": "George Town",
  "GGW": "Glasgow",
  "GHA": "Ghardala",
  "GHB": "Governors Harbour",
  "GHE": "Garachine",
  "GHT": "Ghat",
  "GIB": "Gibraltar",
  "GIC": "Boiju Island",
  "GIG": "Rio De Janeiro",
  "GIL": "Gilgit",
  "GIS": "Gisborne",
  "GIZ": "Gizan",
  "GJA": "Guanaja",
  "GJL": "Jijel",
  "GJT": "Grand Junction",
  "GKA": "Goroka",
  "GLF": "Golfito",
  "GLH": "Greenville",
  "GLI": "Glen Innes",
  "GLT": "Gladstone",
  "GLV": "Golovin",
  "GMB": "Gambela",
  "GNB": "Grenoble",
  "GND": "Grenada",
  "GNU": "Goodnews Bay",
  "GNV": "Gainesville",
  "GOA": "Genoa",
  "GOB": "Goba",
  "GOE": "Gonalia",
  "GOH": "Nuuk",
  "GOI": "Goa",
  "GOJ": "Nizhniy Novgorod",
  "GON": "Groton/New London",
  "GOQ": "Golmud",
  "GOR": "Gore",
  "GOT": "Gothenburg",
  "GOV": "Gove",
  "GPA": "Patras",
  "GPN": "Garden Point",
  "GPS": "Galapagos",
  "GPT": "Gulfport",
  "GRB": "Green Bay",
  "GRI": "Grand Island",
  "GRJ": "George",
  "GRL": "Garasa",
  "GRO": "Gerona",
  "GRQ": "Groningen",
  "GRR": "Grand Rapids",
  "GRU": "Sao Paulo",
  "GRW": "Graciosa Island",
  "GRX": "Granada, Spain",
  "GRY": "Grimsey",
  "GRZ": "Graz",
  "GSO": "Greensboro",
  "GSP": "Greenville/spartanburg",
  "GST": "Gustavus",
  "GTE": "Groofe Eylandt",
  "GTF": "Great Falls",
  "GTO": "Gorontalo",
  "GUA": "Guatemala City",
  "GUB": "Guerrero Negro",
  "GUC": "Gunnison",
  "GUD": "Goundam",
  "GUI": "Guiria",
  "GUM": "Guam",
  "GUP": "Gallup",
  "GUR": "Alotau",
  "GUW": "Atyrau",
  "GVA": "Geneva",
  "GVR": "Governador Valadares",
  "GWD": "Gwadar",
  "GWL": "Gwalior",
  "GWT": "Westerland",
  "GWY": "Galway",
  "GXF": "Seiyun",
  "GYA": "Guayaramerin",
  "GYE": "Guayaquil",
  "GYL": "Argyle",
  "GYM": "Guaymas",
  "GYN": "Goiania",
  "GYY": "Gary",
  "GZA": "Gaza City",
  "GZM": "Gozo",
  "GZO": "Gizo",
  "GZT": "Gaziatep",
  "HAA": "Hasvik",
  "HAC": "Hachijo Jima",
  "HAD": "Halmstad",
  "HAE": "Havasupai",
  "HAH": "Moroni",
  "HAK": "Haikou",
  "HAM": "Hamburg",
  "HAN": "Hanoi",
  "HAP": "Long Island",
  "HAQ": "Hanimaadhoo",
  "HAS": "Hail",
  "HAU": "Haugesund",
  "HAV": "Havana",
  "HBA": "Hobart",
  "HBB": "Hobbs",
  "HBE": "Borg El Arab",
  "HCQ": "Halls Creek",
  "HCR": "Holy Cross",
  "HDB": "Heidelberg",
  "HDF": "Heringsdorf",
  "HDN": "Hayden",
  "HDS": "Hoedspruit",
  "HDY": "Hat Yai",
  "HEH": "Heno",
  "HEL": "Helsinki",
  "HER": "Heraklian",
  "HET": "Hohhot",
  "HFA": "Haifa",
  "HFE": "Hefei",
  "HFN": "Hornafjordur",
  "HFS": "Hagfors",
  "HFT": "Hammerfest",
  "HGA": "Hargeisa",
  "HGD": "Hughenden",
  "HGH": "Hangzhou",
  "HGL": "Helgoland",
  "HGN": "Mae Hong Son",
  "HGR": "Hagerstown",
  "HGU": "Mount Hagen",
  "HHH": "Hilton Head",
  "HHN": "Frankfurt",
  "HHQ": "Hualtin",
  "HIB": "Hibbing/Chisholm",
  "HID": "Horn Island Australia",
  "HII": "Lake Havasu City",
  "HIJ": "Hiroshima",
  "HIL": "Shillavo",
  "HIN": "Jinju",
  "HIR": "Honiara",
  "HIS": "Hayman Island",
  "HIT": "Hivaro",
  "HJR": "Khajuraho",
  "HKB": "Healy Lake",
  "HKD": "Hakodate",
  "HKG": "Hong Kong",
  "HKK": "Hokitika",
  "HKN": "Hoskins",
  "HKT": "Phuket",
  "HKY": "Hickory",
  "HLD": "Hailar",
  "HLF": "Hultsfred",
  "HLH": "Ulanhot",
  "HLN": "Helena",
  "HME": "Hassi Messaoud",
  "HMO": "Hermosillo",
  "HMV": "Hermavan",
  "HNA": "Morioka",
  "HND": "Tokyo",
  "HNH": "Hoonah",
  "HNL": "Honolulu",
  "HNM": "Hana",
  "HNS": "Haines",
  "HOD": "Hodeidah",
  "HOE": "Houeisay",
  "HOF": "Hofuf",
  "HOG": "Holguin",
  "HOK": "Hooker",
  "HOM": "Homer",
  "HON": "Huron",
  "HOQ": "Hof",
  "HOR": "Horta",
  "HOT": "Hot Springs",
  "HOU": "Houston",
  "HOV": "Orsta-Volda",
  "HPA": "Haapa",
  "HPB": "Hooper Bay",
  "HPH": "Haiphong",
  "HPN": "Westchester County",
  "HRB": "Harbin",
  "HRE": "Harare",
  "HRG": "Hurghada",
  "HRK": "Kharkov",
  "HRL": "Harlingen",
  "HRO": "Harrison",
  "HSL": "Huslia",
  "HSN": "Zhoushan",
  "HSV": "Huntsville",
  "HTA": "Chita",
  "HTI": "Hamilton Island",
  "HTN": "Hotan",
  "HTR": "Hateruma",
  "HTS": "Huntington",
  "HUF": "Terre Haute",
  "HUH": "Huahine",
  "HUI": "Hue",
  "HUN": "Hualien",
  "HUQ": "Houn",
  "HUS": "Hughes",
  "HUU": "Huanuco",
  "HUV": "Hudiksvall",
  "HUX": "Huatulco",
  "HUY": "Humberside",
  "HVA": "Analalava",
  "HVB": "Hervey Bay",
  "HVG": "Honningsvag",
  "HVN": "New Haven",
  "HVR": "Havre",
  "HWN": "Hwange Nat Park",
  "HYA": "Hyannis",
  "HYD": "Hyderabad",
  "HYG": "Hydaburg",
  "HYL": "Hollis",
  "HYN": "Huargyan",
  "HYS": "Hays",
  "HZG": "Hanzhang",
  "IAA": "Igarka",
  "IAD": "Washington Dc - Dulles",
  "IAM": "In Amenas",
  "IAN": "Kiana",
  "IAR": "Yaroslavl",
  "IAS": "Iasi",
  "IBE": "Ibague",
  "IBZ": "Ibiza",
  "ICI": "Cicia",
  "ICN": "Seoul",
  "ICT": "Wichita",
  "IDA": "Idaho Falls",
  "IDN": "Indagen",
  "IDR": "Indore",
  "IEG": "Zielana",
  "IEV": "Kiev",
  "IFJ": "Isafjordur",
  "IFN": "Isfahan",
  "IFO": "Ivano-Frankovsk",
  "IFP": "Bullhead City/Laughlin",
  "IGA": "Inagua",
  "IGG": "Igiugig",
  "IGM": "Kingman",
  "IGR": "Iguazu",
  "IGU": "Iguassu Falls",
  "IHU": "Ihu",
  "IKO": "Nikolski",
  "IKS": "Tiksi",
  "IKT": "Irkutsk",
  "ILA": "Illaga",
  "ILE": "Killeen",
  "ILF": "Ilford",
  "ILI": "Iliamna",
  "ILM": "Wilmington",
  "ILO": "Iloilo",
  "ILP": "Ile Des Pins",
  "ILY": "Islay",
  "IMF": "Imphal",
  "IMP": "Imperatriz",
  "IMT": "Iron Mountain",
  "INA": "Inta",
  "INC": "Yinchuan",
  "IND": "Indianapolis",
  "ING": "Lago Argentina",
  "INL": "International Falls",
  "INN": "Innsbruck",
  "INU": "Nauru Island",
  "INV": "Inverness",
  "INX": "Inanwatan",
  "IOA": "Ioannina",
  "IOM": "Isle Of Man",
  "IOP": "Ioma",
  "IOS": "Ilheus",
  "IPA": "Ipota",
  "IPE": "Ipil",
  "IPH": "Ipoh",
  "IPI": "Ipiales",
  "IPL": "Imperial",
  "IPN": "Ipatinga",
  "IPT": "Williamsport",
  "IQM": "Qiemo",
  "IQQ": "Iquique",
  "IQT": "Iquitos",
  "IRA": "Kirakira",
  "IRC": "Circle",
  "IRG": "Lockhart River",
  "IRJ": "La Rioja",
  "IRK": "Kirksville",
  "ISA": "Mount Isa",
  "ISB": "Islamabad",
  "ISC": "Isles Of Scilly",
  "ISG": "Ishigakij",
  "ISN": "Williston",
  "ISP": "Islip",
  "IST": "Istanbul",
  "ITB": "Itaituba",
  "ITH": "Ithaca",
  "ITK": "Itokama",
  "ITO": "Hilo",
  "IUE": "Niue Island",
  "IUL": "Ilu",
  "IVA": "Ambanja",
  "IVC": "Invercargill",
  "IVL": "Ivalo",
  "IVR": "Inverell",
  "IWD": "Ironwood",
  "IWJ": "Iwami",
  "IXA": "Agartala",
  "IXB": "Bagdogra",
  "IXC": "Chandigarh",
  "IXE": "Mangalore",
  "IXJ": "Jommu",
  "IXL": "Leh",
  "IXM": "Madurai",
  "IXR": "Ranchi",
  "IXS": "Silchar",
  "IXU": "Aurangabad",
  "IXZ": "Port Blair",
  "IYK": "Inyokern",
  "IZO": "Izumo",
  "IZT": "Ixtepec",
  "JAC": "Jackson Hole",
  "JAG": "Jacobabad",
  "JAI": "Jaipur",
  "JAL": "Jalapa",
  "JAN": "Jackson",
  "JAQ": "Jacquinot Bay",
  "JAT": "Jabor",
  "JAV": "Ilulissat",
  "JAX": "Jacksonville",
  "JBR": "Jonesboro",
  "JCK": "Julia Creek",
  "JCR": "Jacareacanga",
  "JCU": "Ceuta",
  "JDF": "Juiz De Fora",
  "JDH": "Jodhpur",
  "JDO": "Juazeiro Do Norte",
  "JDZ": "Jingdezhen",
  "JED": "Jeddah",
  "JEG": "Aasiaat",
  "JEJ": "Jeh",
  "JER": "Jersey",
  "JFK": "New York",
  "JFR": "Paamiut",
  "JGA": "Jamnagar",
  "JGN": "Jiayuguan",
  "JGR": "Groennedal",
  "JHB": "Johor",
  "JHE": "Angelholm/Helsingborg",
  "JHG": "Jinghong",
  "JHM": "Kapalua",
  "JHQ": "Shute Harbor",
  "JHS": "Sisimiut",
  "JIB": "Djibouti",
  "JIJ": "Jijiga",
  "JIM": "Jimma",
  "JIN": "Jinja",
  "JIW": "Jiwani",
  "JJN": "Jinjiang",
  "JJU": "Qaqortoq",
  "JKG": "Jonkoping",
  "JKR": "Janakpur",
  "JLN": "Joplin",
  "JMK": "Mikonos",
  "JMO": "Jomsom",
  "JMS": "Jamestown",
  "JMU": "Jiamusi",
  "JNB": "Johannesburg",
  "JNN": "Nanortalik",
  "JNS": "Narsaq",
  "JNU": "Juneau",
  "JNZ": "Jinzhou",
  "JOE": "Joensuu",
  "JOG": "Yogyakarta",
  "JOI": "Joinville",
  "JON": "Johnston Island",
  "JPA": "Joao Pessoa",
  "JPR": "Ji-Parana",
  "JQE": "Jaque",
  "JRH": "Jorhat",
  "JRO": "Serengeti",
  "JSI": "Skiathos",
  "JSM": "Jose De San Martin",
  "JSR": "Jessore",
  "JST": "Johnstown",
  "JSU": "Mariitsoq",
  "JTR": "Thira",
  "JUI": "Juist",
  "JUJ": "Jujuy",
  "JUL": "Juliaca",
  "JUV": "Upernavik",
  "JUZ": "Juzha",
  "JVA": "Ankavandra",
  "JVL": "Janesville",
  "JYV": "Jyvaskyla",
  "KAA": "Kasama",
  "KAB": "Kariba",
  "KAC": "Kameshli",
  "KAE": "Kake",
  "KAG": "Gangneung",
  "KAJ": "Kajaani",
  "KAL": "Kaltag",
  "KAN": "Kano",
  "KAO": "Kuusamo",
  "KAT": "Kaitaia",
  "KAW": "Kawthaung",
  "KAX": "Kalbarri",
  "KBC": "Birch Creek",
  "KBF": "Karubaga",
  "KBL": "Kabul",
  "KBM": "Kabwun",
  "KBR": "Kota Bharu",
  "KBT": "Kaben",
  "KBV": "Krabi",
  "KBX": "Kambuaya",
  "KCC": "Coffman Cove",
  "KCD": "Kamur",
  "KCF": "Kadanwari",
  "KCG": "Chignik",
  "KCH": "Kuching",
  "KCM": "Kahramanmaras",
  "KCZ": "Kochi",
  "KDD": "Khuzdar",
  "KDI": "Kendari",
  "KDL": "Kardia",
  "KDM": "Kaadedhdhoo",
  "KDO": "Kadhonoo",
  "KEF": "Iceland",
  "KEK": "Ekwok",
  "KEW": "Keewaywin",
  "KGD": "Kaliningrad",
  "KGK": "New Koliganek",
  "KGL": "Kigali",
  "KGX": "Grayling",
  "KHI": "Karachi",
  "KIF": "Kingfisher Lake",
  "KIN": "Kingston",
  "KIV": "Chisinau",
  "KIX": "Kyoto",
  "KKH": "Kongiganak",
  "KKI": "Akiachak",
  "KKU": "Ekuk",
  "KLG": "Kalskag",
  "KLL": "Levelock",
  "KLW": "Klawock",
  "KMO": "Manokotak",
  "KNK": "Kakhonak",
  "KNW": "New Stuyahok",
  "KOA": "Kona",
  "KOT": "Kotlik",
  "KPB": "Point Baker",
  "KPC": "Port Clarence",
  "KPN": "Kipnuk",
  "KPV": "Perryville",
  "KQA": "Akuton",
  "KRK": "Krakow",
  "KTB": "Thorne Bay",
  "KTD": "Kitadaito",
  "KTM": "Kathmandu",
  "KTN": "Ketchikan",
  "KTR": "Katherine",
  "KTS": "Teller Mission",
  "KTT": "Kittila",
  "KTW": "Katowice",
  "KUA": "Kuantan",
  "KUD": "Kudat",
  "KUG": "Kubin Island",
  "KUH": "Kushiro",
  "KUK": "Kasigluk",
  "KUL": "Kuala Lumpur",
  "KUN": "Kaunas",
  "KUO": "Kuopio",
  "KUQ": "Kuri",
  "KUS": "Kulusuk",
  "KUT": "Kutaisi",
  "KUV": "Gunsan",
  "KUY": "Kamusi",
  "KVA": "Kavala",
  "KVB": "Skovde",
  "KVC": "King Cove",
  "KVD": "Gyandzha",
  "KVG": "Kavieng",
  "KVL": "Kivalina",
  "KWA": "Kwajalein",
  "KWE": "Gulyang",
  "KWF": "Waterfall",
  "KWG": "Krivoy Rog",
  "KWI": "Kuwait",
  "KWJ": "Gwangju",
  "KWK": "Kwigillingok",
  "KWL": "Guilin",
  "KWM": "Kowanyama",
  "KWN": "Quinhagak",
  "KWT": "Kwethluk",
  "KWY": "Kiwayu",
  "KXA": "Kasaan",
  "KXK": "Komsomolsk Na Amure",
  "KYA": "Konya",
  "KYU": "Koyukuk",
  "KYX": "Yalumet",
  "KYZ": "Kyzyl",
  "KZF": "Kaintiba",
  "KZN": "Kazan",
  "LAB": "Lablab",
  "LAD": "Luanda",
  "LAE": "Lae",
  "LAF": "Lafayette",
  "LAI": "Lannion",
  "LAJ": "Lages",
  "LAN": "Lansing",
  "LAO": "Laoag",
  "LAQ": "Beida",
  "LAR": "Laramie",
  "LAS": "Las Vegas",
  "LAU": "Lamu",
  "LAW": "Lawton",
  "LAX": "Los Angeles",
  "LBA": "Leeds",
  "LBB": "Lubbock",
  "LBD": "Khudzhand",
  "LBE": "Latrobe",
  "LBF": "North Platte",
  "LBJ": "Labuan Bajo",
  "LBL": "Liberal",
  "LBP": "Long Banga",
  "LBS": "Labasa",
  "LBU": "Labuan",
  "LBV": "Libreville",
  "LBW": "Long Bawan",
  "LCA": "Larnaca",
  "LCE": "La Ceiba",
  "LCG": "La Coruna",
  "LCH": "Lake Charles",
  "LDB": "Londrina",
  "LDC": "Lindeman Island",
  "LDE": "Lourdes/Tarbes",
  "LDH": "Lord Howe Island",
  "LDI": "Lindi",
  "LDU": "Lahadbatu",
  "LDY": "Londonderry",
  "LEA": "Learmonth",
  "LEB": "Lebanon",
  "LED": "St. Petersburg",
  "LEH": "Le Havre",
  "LEI": "Almeria",
  "LEJ": "Leipzig",
  "LEQ": "Lands End",
  "LER": "Leinster",
  "LET": "Leticia",
  "LEV": "Bureta",
  "LEX": "Lexington",
  "LFW": "Lome",
  "LGB": "Long Beach",
  "LGG": "Liege",
  "LGI": "Long Island/Deadmans Cay",
  "LGK": "Langkawi",
  "LGL": "Long Lellang",
  "LGP": "Legaspi",
  "LGQ": "Lago Agrio",
  "LGS": "Malargue",
  "LHE": "Lahore",
  "LHG": "Lightning Ridge",
  "LHR": "London",
  "LHW": "Lanzhau",
  "LIF": "Lifa",
  "LIG": "Limoges",
  "LIH": "Lihue",
  "LII": "Mulia",
  "LIK": "Likiep Island",
  "LIL": "Lille",
  "LIM": "Lima",
  "LIR": "Liberia",
  "LIS": "Lisbon",
  "LIT": "Little Rock",
  "LJG": "Lijiang City",
  "LJU": "Ljubliana",
  "LKA": "Larantuka",
  "LKB": "Lakeba",
  "LKL": "Lakselv",
  "LKN": "Leknes",
  "LKO": "Lucknow",
  "LLA": "Lulea",
  "LLI": "Lalibela",
  "LLW": "Lilongwe",
  "LMA": "Lake Minchumina",
  "LML": "Lae Island",
  "LMM": "Los Mochis",
  "LMN": "Limbang",
  "LMP": "Lampedusa",
  "LMT": "Klamath Falls",
  "LNB": "Lamen Bay",
  "LNE": "Lonorore",
  "LNK": "Lincoln",
  "LNO": "Leonora",
  "LNS": "Lancaster",
  "LNV": "Lihir Island",
  "LNY": "Lanai",
  "LNZ": "Linz",
  "LOD": "Longana",
  "LOF": "Loen",
  "LOH": "Loja",
  "LOS": "Lagos",
  "LOV": "Monclova",
  "LPA": "Las Palmas",
  "LPB": "La Paz",
  "LPI": "Lampang",
  "LPL": "Liverpool",
  "LPM": "Lamap",
  "LPP": "Lappeenranta",
  "LPQ": "Luang Prabang",
  "LPS": "Lopez Island",
  "LPU": "Long Apung",
  "LPY": "Le Puy",
  "LRD": "Laredo",
  "LRE": "Longreach",
  "LRH": "Larochelle",
  "LRM": "La Romana",
  "LRT": "Lorient",
  "LSA": "Losuia",
  "LSC": "La Serena",
  "LSE": "La Crosse",
  "LSP": "Las Piedras",
  "LST": "Launceston",
  "LSY": "Lismore",
  "LTD": "Ghadames",
  "LTK": "Latakia",
  "LTO": "Loreto",
  "LTQ": "Le Touquet",
  "LTT": "Saint Tropez",
  "LUA": "Lukla",
  "LUC": "Laucala Island",
  "LUD": "Luderitz",
  "LUG": "Lugano",
  "LUM": "Luxi",
  "LUN": "Lusaka",
  "LUP": "Kalaupapa",
  "LUQ": "San Luis",
  "LUR": "Cape Lisburne",
  "LUV": "Langguri",
  "LUW": "Luwuk",
  "LUX": "Luxembourg",
  "LVI": "Livingstone",
  "LVO": "Laverton",
  "LWB": "Lewisburg",
  "LWK": "Shetland Islands",
  "LWN": "Gyourmri",
  "LWO": "Lvov",
  "LWS": "Lewiston",
  "LWT": "Lewistown",
  "LWY": "Lawas",
  "LXA": "Lhasa",
  "LXG": "Luang Namtha",
  "LXR": "Luxor",
  "LXS": "Lemnos",
  "LYA": "Luoyang",
  "LYC": "Lyoksele",
  "LYG": "Lianyungang",
  "LYI": "Linyi",
  "LYP": "Faisalabad",
  "LYR": "Longyearbyen",
  "LYS": "Lyon",
  "LYU": "Ely",
  "LZC": "Lozaro Cardenas",
  "LZH": "Liuzhou",
  "LZO": "Luzhou",
  "LZR": "Lizard Island",
  "MAA": "Chennai",
  "MAB": "Maraba",
  "MAD": "Madrid",
  "MAF": "Midland/Odessa",
  "MAG": "Madang",
  "MAH": "Menorca",
  "MAJ": "Majuro",
  "MAK": "Malakai",
  "MAM": "Matamoros",
  "MAO": "Manaus",
  "MAQ": "Mae Sot",
  "MAR": "Maracaibo",
  "MAS": "Manus Island",
  "MAT": "Natadi",
  "MAU": "Maupiti",
  "MAV": "Maloelap Island",
  "MAY": "Mangrove Cay",
  "MAZ": "Mayaguez",
  "MBA": "Mombasa",
  "MBE": "Monbetsu",
  "MBH": "Maryborough",
  "MBJ": "Montego Bay",
  "MBL": "Manistee",
  "MBS": "Midland",
  "MBT": "Masbate",
  "MBX": "Maribor",
  "MCE": "Merced",
  "MCG": "Mcgrath",
  "MCH": "Machala",
  "MCI": "Kansas City",
  "MCK": "Mccook",
  "MCM": "Monte Carlo",
  "MCN": "Macon",
  "MCO": "Orlando",
  "MCP": "Macapa",
  "MCT": "Muscat",
  "MCV": "Mcarthur River",
  "MCW": "Mason City",
  "MCX": "Makhachkala",
  "MCY": "Sunshine Coast",
  "MCZ": "Maceio",
  "MDC": "Manado",
  "MDE": "Medellin",
  "MDG": "Mudanjiang",
  "MDH": "Carbondale",
  "MDJ": "Madras",
  "MDK": "Mbandaka",
  "MDL": "Mandalay",
  "MDP": "Mindiptana",
  "MDQ": "Mar Del Plata",
  "MDS": "Middle Caicos",
  "MDT": "Harrisburg",
  "MDY": "Midway Island",
  "MDZ": "Mendoza",
  "MEC": "Manta",
  "MED": "Madinah",
  "MEE": "Mare",
  "MEH": "Mehamn",
  "MEI": "Meridian",
  "MEL": "Melbourne",
  "MEM": "Memphis",
  "MES": "Medan",
  "MEU": "Monte Dourado",
  "MEX": "Mexico City",
  "MFA": "Mafia",
  "MFE": "Mcallen",
  "MFG": "Muzaffarabad",
  "MFJ": "Moala",
  "MFM": "Macau",
  "MFO": "Manguna",
  "MFR": "Medford",
  "MFU": "Mfume",
  "MGA": "Managua",
  "MGB": "Mount Gambier",
  "MGF": "Maringa",
  "MGH": "Margate",
  "MGM": "Montgomery",
  "MGQ": "Mogadishu",
  "MGS": "Mangaia Island",
  "MGT": "Milingimbi",
  "MGW": "Morgantown",
  "MGZ": "Myeik",
  "MHD": "Mashad",
  "MHG": "Mannheim",
  "MHH": "Marsh Harbour",
  "MHK": "Manhattan",
  "MHP": "Minsk",
  "MHQ": "Mariehamn",
  "MHT": "Manchester",
  "MHU": "Mount Hotham",
  "MHX": "Manihiki Island",
  "MIA": "Miami",
  "MID": "Merida",
  "MII": "Marilia",
  "MIJ": "Mili Island",
  "MIK": "Mikkeli",
  "MIM": "Merimbula",
  "MIR": "Monastir",
  "MIS": "Misima Island",
  "MJA": "Manja",
  "MJB": "Mejit Island",
  "MJD": "Mohenjodaro",
  "MJE": "Majkin",
  "MJF": "Mosjoen",
  "MJK": "Monkey Mia",
  "MJL": "Mouila",
  "MJM": "Mbuji Mayi",
  "MJN": "Majunga",
  "MJT": "Mytilene",
  "MJV": "Murcia",
  "MJZ": "Mirnyj",
  "MKE": "Milwaukee",
  "MKG": "Muskegon",
  "MKK": "Molokai",
  "MKM": "Mukan",
  "MKQ": "Merauke",
  "MKR": "Meekatharra",
  "MKS": "Mekane Selam",
  "MKT": "Mankato",
  "MKU": "Makokou",
  "MKW": "Manokwari",
  "MKY": "Mackay",
  "MKZ": "Malacca",
  "MLA": "Malta",
  "MLE": "Male",
  "MLH": "Mulhouse",
  "MLI": "Moline",
  "MLL": "Marshall",
  "MLM": "Morelia",
  "MLN": "Melilla",
  "MLS": "Miles City",
  "MLU": "Monroe",
  "MLX": "Malatya",
  "MLY": "Manley Hot Springs",
  "MMB": "Memanbetsu",
  "MMD": "Minami Daito",
  "MME": "Teesside",
  "MMG": "Mount Magnet",
  "MMJ": "Matsumoto",
  "MMK": "Murmansk",
  "MMO": "Maio",
  "MMX": "Malmo",
  "MMY": "Miyako Jima",
  "MNB": "Moanda",
  "MNC": "Nacala",
  "MNF": "Mana Island",
  "MNG": "Maningrioa",
  "MNI": "Montserrat",
  "MNJ": "Mananjary",
  "MNL": "Manila",
  "MNR": "Mangu",
  "MNT": "Minto",
  "MNU": "Maulmyine",
  "MNY": "Mono",
  "MOA": "Moa",
  "MOB": "Mobile",
  "MOC": "Montes Claros",
  "MOD": "Modesto",
  "MOF": "Maumere",
  "MOI": "Mitiaro Island",
  "MOL": "Molde",
  "MON": "Mount Cook",
  "MOQ": "Morondava",
  "MOT": "Minot",
  "MOU": "Mountain Village",
  "MOV": "Moranbah",
  "MOW": "Moscow",
  "MPA": "Mpacha",
  "MPK": "Mokpo",
  "MPL": "Montpellier",
  "MPM": "Maputo",
  "MPN": "Mount Pleasant",
  "MPW": "Mariupol",
  "MQF": "Magnitogorsk",
  "MQL": "Mildura",
  "MQN": "Mo I Rana",
  "MQT": "Marquette",
  "MQX": "Makale",
  "MRA": "Misurata",
  "MRE": "Mara Lodges",
  "MRS": "Marseille",
  "MRU": "Mauritius",
  "MRV": "Mineralnye Vody",
  "MRY": "Monterey",
  "MRZ": "Moree",
  "MSA": "Muskrat Dam",
  "MSE": "Manston",
  "MSJ": "Misawa",
  "MSL": "Muscle Shoals",
  "MSN": "Madison",
  "MSO": "Missoula",
  "MSP": "Minneapolis",
  "MSR": "Mus",
  "MSS": "Massena",
  "MST": "Maastricht",
  "MSU": "Maseru",
  "MSY": "New Orleans",
  "MTF": "Mizan Teferi",
  "MTJ": "Montrose",
  "MTM": "Metlakatla",
  "MTR": "Monteria",
  "MTS": "Manzini",
  "MTT": "Minatitla",
  "MTV": "Mota Lava",
  "MTY": "Monterrey",
  "MUA": "Munda",
  "MUB": "Maun",
  "MUC": "Munich",
  "MUE": "Kamuela",
  "MUH": "Mersa Matruh",
  "MUK": "Mauke Island",
  "MUN": "Maturin",
  "MUR": "Marudi",
  "MUX": "Multan",
  "MUZ": "Musoma",
  "MVB": "Franceville",
  "MVD": "Montevideo",
  "MVR": "Marova",
  "MVS": "Mucuri",
  "MVY": "Marthas Vineyard",
  "MWA": "Marion",
  "MWE": "Merave",
  "MWF": "Maewo",
  "MWH": "Moses Lake",
  "MWZ": "Mwanza",
  "MXH": "Moro",
  "MXL": "Mexicali",
  "MXM": "Morambe",
  "MXP": "Milan",
  "MXS": "Maota Savaii Is",
  "MXT": "Maintirano",
  "MXX": "Mora",
  "MXZ": "Meixian",
  "MYA": "Moruya",
  "MYC": "Maracay",
  "MYD": "Malindi",
  "MYE": "Miyakejima",
  "MYG": "Mayaguana",
  "MYI": "Murray Island",
  "MYJ": "Matsuyama",
  "MYR": "Myrtle Beach",
  "MYT": "Myitkyina",
  "MYU": "Mekoryuk",
  "MYW": "Mtwara",
  "MYX": "Menyamya",
  "MYY": "Miri",
  "MZG": "Makung",
  "MZI": "Mopti",
  "MZL": "Manizales",
  "MZO": "Manzanillo",
  "MZT": "Mazatlan",
  "MZV": "Mulu",
  "NAA": "Narrabri",
  "NAG": "Nagpur",
  "NAJ": "Nakhichevan",
  "NAK": "Nakhon Ratchosima",
  "NAL": "Nalchik",
  "NAN": "Nadi",
  "NAO": "Nanchong",
  "NAP": "Capri",
  "NAS": "Nassau",
  "NAT": "Natal",
  "NAW": "Narathiwat",
  "NBO": "Nairobi",
  "NBX": "Nabire",
  "NCA": "North Caicos",
  "NCE": "Nice",
  "NCN": "New Chenega",
  "NCU": "Nukus",
  "NCY": "Annecy",
  "NDB": "Nouadhiba",
  "NDG": "Qiqihar",
  "NDI": "Namudi",
  "NDJ": "Ndjamena",
  "NDK": "Namorik Island",
  "NDM": "Mendi",
  "NDR": "Nadar",
  "NDY": "Sanday",
  "NDZ": "Nordholz-Speika",
  "NER": "Neryjungri",
  "NEV": "Nevis",
  "NFG": "Nefteyugansk",
  "NFO": "Nukulaelae",
  "NGB": "Ningbo",
  "NGE": "Ngaoundere",
  "NGI": "Ngau Island",
  "NGO": "Nagoya",
  "NGS": "Nagasaki",
  "NGX": "Manang",
  "NHA": "Nha Trang",
  "NHV": "Nuku Hiva",
  "NIB": "Nikolai",
  "NIC": "Nicosia",
  "NIM": "Niamey",
  "NIX": "Nioko",
  "NJC": "Nizhnevartovsk",
  "NKC": "Nouakchott",
  "NKD": "Sinak",
  "NKG": "Nanking/Nanjing",
  "NKI": "Naukiti",
  "NLA": "Ndola",
  "NLD": "Nuevo Laredo",
  "NLF": "Darnley Island",
  "NLG": "Nelson Lagoon",
  "NLK": "Norfolk Island",
  "NLP": "Nelspruit",
  "NMA": "Namangan",
  "NME": "Nightmute",
  "NMG": "San Miguel",
  "NNG": "Nanning",
  "NNL": "Nondalton",
  "NNM": "Naryan-Mar",
  "NNT": "Nan",
  "NNX": "Nunukan",
  "NNY": "Nanyang",
  "NOB": "Nosara Beach",
  "NOC": "Knock",
  "NOJ": "Nojabrxsk",
  "NOS": "Nossi-Be",
  "NOU": "Noumea",
  "NOZ": "Novokuznetsk",
  "NPE": "Napier-Hastings",
  "NPL": "New Plymouth",
  "NQN": "Neuquen",
  "NQY": "Newquay",
  "NRD": "Norderney",
  "NRK": "Norrkoping",
  "NRL": "North Ronaldsay",
  "NRT": "Tokyo",
  "NSN": "Nelso",
  "NST": "Nakhon Si Thammarat",
  "NTE": "Nantes",
  "NTG": "Nantong",
  "NTI": "Bintuni",
  "NTN": "Normanton",
  "NTO": "Santo Antao",
  "NTT": "Niuatoputapu",
  "NTY": "Sun City",
  "NUB": "Numbulwar",
  "NUI": "Nuiqsut",
  "NUL": "Nulato",
  "NUP": "Nunapitchuk",
  "NUS": "Norsup",
  "NUX": "Nayurengoy",
  "NVA": "Neiva",
  "NVK": "Narvik",
  "NVR": "Novgorod",
  "NVT": "Navegantes",
  "NWI": "Norwich",
  "NYK": "Nanyuki",
  "NYM": "Nadym",
  "NYN": "Nyngan",
  "NYU": "Nyaung",
  "OAG": "Orange",
  "OAK": "Oakland",
  "OAX": "Oaxaca",
  "OBD": "Obano",
  "OBO": "Obihiro",
  "OBU": "Kobuk",
  "ODN": "Long Seridan",
  "ODS": "Odessa",
  "ODY": "Oudomxay",
  "OER": "Ornskoldsvik",
  "OES": "San Antonio Oesta",
  "OFK": "Norfolk",
  "OGG": "Maui",
  "OGN": "Yonaguni Jima",
  "OGS": "Ogdensburg",
  "OGX": "Ouargla",
  "OGZ": "Vladikavkaz",
  "OHD": "Ohrid",
  "OHO": "Okhotsk",
  "OIM": "Oshima",
  "OIR": "Okoshiri",
  "OIT": "Oita",
  "OKA": "Okinawa",
  "OKC": "Oklahoma City",
  "OKJ": "Okayama",
  "OKL": "Oksibil",
  "OKQ": "Okaba",
  "OKR": "Yorke Island",
  "OKU": "Mokuti Lodge",
  "OLB": "Olbia",
  "OLJ": "Olpoi",
  "OLP": "Olympic Dam",
  "OMA": "Omaha",
  "OMB": "Omboue",
  "OMD": "Oranjemund",
  "OME": "Nome",
  "OMH": "Urmieh",
  "OMO": "Mostar",
  "OMR": "Oradea",
  "OMS": "Omsk",
  "OND": "Ondangwa",
  "ONG": "Mornington",
  "ONI": "Moanamani",
  "ONT": "Ontario",
  "ONX": "Colon",
  "OOK": "Toksook Bay",
  "OOL": "Gold Coast",
  "OOM": "Cooma",
  "OPO": "Porto",
  "OPU": "Balimo",
  "ORB": "Orebro",
  "ORD": "Chicago",
  "ORH": "Worcester",
  "ORK": "Cork",
  "ORN": "Oran",
  "ORT": "Northway",
  "ORV": "Noorvik",
  "ORW": "Ormara",
  "OSD": "Ostersund",
  "OSH": "Oshkosh",
  "OSI": "Osijek",
  "OSK": "Oskarshamn",
  "OSL": "Oslo",
  "OSR": "Ostrava",
  "OSW": "Orsk",
  "OSY": "Namsos",
  "OSZ": "Koszalin",
  "OTD": "Contadora",
  "OTH": "North Bend",
  "OTM": "Ottumwa",
  "OTU": "Otu",
  "OTZ": "Kotzebue",
  "OUA": "Ouagadougou",
  "OUD": "Oujda",
  "OUL": "Oulu",
  "OUZ": "Zouerate",
  "OVB": "Novosibirsk",
  "OVD": "Asturias",
  "OWB": "Owensboro",
  "OXB": "Bissau",
  "OXR": "Oxnard/Ventura",
  "OYA": "Goya",
  "OYE": "Oyem",
  "OZH": "Zaporozhye",
  "OZZ": "Ouarzazate",
  "PAD": "Paderborn",
  "PAF": "Pakuba",
  "PAH": "Paducah",
  "PAJ": "Para Chinar",
  "PAK": "Hanapepe",
  "PAP": "Port Au Prince",
  "PAT": "Patna",
  "PAZ": "Poza Rico",
  "PBC": "Puebla",
  "PBD": "Porbandar",
  "PBE": "Puerto Berria",
  "PBH": "Paro",
  "PBI": "West Palm Beach",
  "PBJ": "Paama",
  "PBM": "Paramaribo",
  "PBO": "Paraburdoo",
  "PBP": "Punta Islita",
  "PBZ": "Plettenburg Bay",
  "PCA": "Portage Creek",
  "PCH": "Palacios",
  "PCL": "Pucallpa",
  "PDB": "Pedro Bay",
  "PDG": "Padang",
  "PDL": "Ponta Delgada",
  "PDP": "Punta Del Este",
  "PDS": "Piedras Negras",
  "PDT": "Pendleton",
  "PEC": "Pelican",
  "PEE": "Perm",
  "PEG": "Perugia",
  "PEI": "Pereira",
  "PEK": "Beijing",
  "PEM": "Puerto Maldonado",
  "PEN": "Penang",
  "PER": "Perth",
  "PES": "Petrozavodsk",
  "PET": "Pelotas",
  "PEU": "Puerto Lempira",
  "PEW": "Peshawar",
  "PEX": "Pechora",
  "PFB": "Passo Fundo",
  "PFO": "Paphos",
  "PGA": "Page",
  "PGF": "Perpignan",
  "PGK": "Pangkalpinang",
  "PGX": "Perigueux",
  "PHB": "Parnaiba",
  "PHC": "Port Harcourt",
  "PHE": "Port Headland",
  "PHF": "Hampton",
  "PHL": "Philadelphia",
  "PHO": "Point Hope",
  "PHS": "Phitsanulok",
  "PHW": "Phalaborwa",
  "PHX": "Phoenix",
  "PIA": "Peoria",
  "PIB": "Laurel",
  "PID": "Paradise Island",
  "PIE": "Clearwater/st Petersburg",
  "PIF": "Pingtung",
  "PIH": "Pocatello",
  "PIR": "Pierre",
  "PIS": "Poitiers",
  "PIT": "Pittsburgh",
  "PIU": "Piura",
  "PIX": "Pico Island",
  "PIZ": "Point Lay",
  "PJG": "Panjger",
  "PJM": "Puerto Jimenez",
  "PKA": "Napaskiak",
  "PKB": "Parkersburg",
  "PKC": "Petropaulousk-Kamchats",
  "PKN": "Pangkalanboun",
  "PKR": "Pokhara",
  "PKU": "Pekanbaru",
  "PKY": "Palang Karaya",
  "PKZ": "Pakse",
  "PLB": "Plattsburgh",
  "PLH": "Plymouth",
  "PLM": "Palembang",
  "PLN": "Pellston",
  "PLO": "Port Lincoln",
  "PLP": "La Palma",
  "PLQ": "Palanga",
  "PLS": "Providenciales",
  "PLV": "Poltava",
  "PLW": "Palu",
  "PLZ": "Port Elizabeth",
  "PMC": "Puerto Montt",
  "PMF": "Parma/Milan",
  "PMG": "Ponta Pora",
  "PMI": "Palma Mallorca",
  "PML": "Port Moller",
  "PMO": "Palermo",
  "PMQ": "Perito Moreno",
  "PMR": "Palmerston North",
  "PMV": "Porlamar",
  "PMW": "Palmas",
  "PMY": "Puerto Madryn",
  "PMZ": "Palmar",
  "PNA": "Pamplona",
  "PNC": "Ponca City",
  "PND": "Punta Gorda",
  "PNH": "Phnom Penh",
  "PNI": "Pohnpei",
  "PNK": "Pontianak",
  "PNL": "Pantelleria",
  "PNP": "Popondetta",
  "PNQ": "Pune",
  "PNR": "Pointe Noire",
  "PNS": "Pensacola",
  "PNZ": "Petrolina",
  "POA": "Porto Alegre",
  "POG": "Port Gentil",
  "POL": "Pemba",
  "POM": "Port Moresby",
  "POP": "Puerto Plata",
  "POR": "Pori",
  "POS": "Port Of Spain",
  "POT": "Port Antonio",
  "POU": "Poughkeepsie",
  "POZ": "Poznan",
  "PPB": "Presidente Prudente",
  "PPG": "Pago Pago",
  "PPP": "Proserpine",
  "PPS": "Puerto Princesa",
  "PPT": "Tahiti",
  "PPV": "Port Protection",
  "PPW": "Papa Westray",
  "PQC": "Phu Quoc",
  "PQI": "Presque Isle",
  "PQM": "Palenque",
  "PQQ": "Port Macquarie",
  "PQS": "Pilot Station",
  "PRA": "Parana",
  "PRC": "Prescott",
  "PRG": "Prague",
  "PRH": "Phrae",
  "PRN": "Pristina",
  "PRQ": "Pres. Roque Saenz Pena",
  "PRS": "Parasi",
  "PSA": "Pisa",
  "PSC": "Pasco",
  "PSE": "Ponce",
  "PSG": "Petersburg",
  "PSI": "Pasni",
  "PSM": "Portsmouth",
  "PSO": "Pasto",
  "PSP": "Palm Springs",
  "PSR": "Pescara",
  "PSS": "Posadas",
  "PSU": "Putussibau",
  "PSY": "Port Stanley",
  "PSZ": "Puerto Suarez",
  "PTA": "Port Alsworth",
  "PTF": "Malololailai",
  "PTG": "Pietersburb",
  "PTH": "Port Heiden",
  "PTP": "Pointe-A-Pitre",
  "PTU": "Platinum",
  "PTY": "Panama City",
  "PUB": "Pueblo",
  "PUD": "Puerto Deseado",
  "PUF": "Pau",
  "PUG": "Port Augusta",
  "PUJ": "Punta Cana",
  "PUQ": "Punta Arenas",
  "PUS": "Busan",
  "PUT": "Puttaparthi",
  "PUW": "Pullman",
  "PUY": "Pula",
  "PVC": "Provincetown",
  "PVD": "Providence",
  "PVG": "Shanghai",
  "PVH": "Porto Velho",
  "PVK": "Preveza/Lefkas",
  "PVO": "Portoviejo",
  "PVR": "Puerto Vallarta",
  "PWM": "Portland",
  "PWQ": "Pavlodar",
  "PXM": "Puerto Escondido",
  "PXO": "Porto Santo",
  "PXU": "Pleiku",
  "PYE": "Penrhyn Island",
  "PYH": "Puerto Ayacucha",
  "PYJ": "Polyarnyj",
  "PZB": "Pietermaritzburg",
  "PZE": "Penzance",
  "PZH": "Zhob",
  "PZO": "Puerto Ordaz",
  "PZU": "Port Sudan",
  "QBC": "Bella Coola",
  "QCE": "Copper Mountain",
  "QFK": "Selje",
  "QFZ": "Saarbruecken",
  "QJY": "Kolobrzeg",
  "QKB": "Breckonridge",
  "QKL": "Cologne",
  "QKS": "Keystone",
  "QQP": "London-Paddington",
  "QRO": "Queretaro",
  "RAB": "Rabaul",
  "RAE": "Arar",
  "RAH": "Rafha",
  "RAI": "Praia",
  "RAJ": "Rajkot",
  "RAK": "Marrakech",
  "RAM": "Ramingining",
  "RAO": "Ribeirao Preto",
  "RAP": "Rapid City",
  "RAR": "Rarotonga",
  "RAS": "Rasht",
  "RAT": "Raduzhnyi",
  "RAZ": "Rawala Kot",
  "RBA": "Rabat",
  "RBE": "Ratanakiri",
  "RBH": "Brooks Lodge",
  "RBJ": "Rebun",
  "RBP": "Rabaraba",
  "RBR": "Rio Branco",
  "RBV": "Ramato",
  "RBY": "Ruby",
  "RCB": "Richards Bay",
  "RCE": "Roche Harbor",
  "RCH": "Riohacha",
  "RCQ": "Reconquista",
  "RCU": "Rio Cuarto",
  "RDD": "Redding",
  "RDE": "Merdey",
  "RDG": "Reading",
  "RDM": "Redmond",
  "RDU": "Raleigh/Durham",
  "RDV": "Red Devil",
  "RDZ": "Rodez",
  "REC": "Recife",
  "REG": "Reggio Calabria",
  "REL": "Trelew",
  "REN": "Orenburg",
  "REP": "Siem Reap",
  "RES": "Resistencia",
  "RET": "Rost",
  "REU": "Reus",
  "REX": "Reynossa",
  "RFP": "Raiatea",
  "RGL": "Rio Gallegos",
  "RGN": "Yangon",
  "RHI": "Rhinelander",
  "RHO": "Rhodes",
  "RIB": "Riberalta",
  "RIC": "Richmond",
  "RIG": "Rio Grande",
  "RIK": "Carrillo",
  "RIS": "Rishiri",
  "RIW": "Riverton",
  "RIX": "Riga",
  "RIY": "Riyan Mukalla",
  "RJH": "Rajshahi",
  "RJK": "Rijeka",
  "RJN": "Rafsanjan",
  "RKD": "Rockland",
  "RKS": "Rock Springs",
  "RKT": "Ras Al Khaimah",
  "RLG": "Rostock-Laage",
  "RMA": "Roma",
  "RMI": "Rimini",
  "RMP": "Rampart",
  "RNB": "Ronneby",
  "RNE": "Roane",
  "RNJ": "Yoronjima",
  "RNL": "Rennell",
  "RNN": "Bornholm",
  "RNO": "Reno",
  "RNP": "Rongelap Island",
  "RNS": "Rennes",
  "ROA": "Roanoke",
  "ROB": "Monrovia",
  "ROK": "Rockhampton",
  "ROP": "Rota",
  "ROR": "Koror",
  "ROT": "Rotorua",
  "ROV": "Rostov",
  "ROW": "Roswell",
  "ROY": "Rio Mayo",
  "RPM": "Ngukurr",
  "RPN": "Rosh Pina",
  "RRG": "Rodrigues Island",
  "RRS": "Roros",
  "RSD": "Rock Sound",
  "RSH": "Russian Mission",
  "RSJ": "Rosario",
  "RST": "Rochester",
  "RSU": "Yeosu",
  "RSW": "Fort Myers",
  "RTB": "Roatan",
  "RTM": "Rotterdam",
  "RTW": "Saratov",
  "RUA": "Arua",
  "RUH": "Riyadh",
  "RUN": "St Denis De La Reunion",
  "RUR": "Rorutu",
  "RUT": "Rutland",
  "RVA": "Farafangana",
  "RVD": "Rio Verde",
  "RVK": "Roervik",
  "RVN": "Rovaniemi",
  "SAF": "Santa Fe",
  "SAH": "Sanaa",
  "SAI": "San Marino",
  "SAL": "San Salvador",
  "SAN": "San Diego",
  "SAP": "San Pedro Sula",
  "SAT": "San Antonio",
  "SAV": "Savannah",
  "SBA": "Santa Barbara",
  "SBN": "South Bend",
  "SBP": "San Luis Obispo",
  "SBS": "Steamboat Springs",
  "SBY": "Salisbury-Ocean City",
  "SCC": "Prudhoe Bay/Deadhorse",
  "SCE": "State College/University Park",
  "SCK": "Stockton",
  "SCL": "Santiago",
  "SCM": "Scammon Bay",
  "SDF": "Louisville",
  "SDL": "Scottsdale",
  "SDP": "Sand Point",
  "SDQ": "Santo Domingo",
  "SEA": "Seattle",
  "SEZ": "Mahe Island",
  "SFO": "Sonoma",
  "SGN": "Saigon",
  "SGU": "Saint George",
  "SGY": "Skagway",
  "SHD": "Staunton",
  "SHG": "Shungnak",
  "SHH": "Shishmaref",
  "SHR": "Sheridan",
  "SHV": "Shreveport",
  "SHX": "Shageluk",
  "SIN": "Singapore",
  "SIT": "Sitka",
  "SJD": "San Jose Del Cabo",
  "SJO": "San Jose",
  "SJT": "San Angelo",
  "SJU": "San Juan",
  "SKB": "St Kitts",
  "SKG": "Thessaloniki",
  "SKK": "Shaktoolik",
  "SLC": "Salt Lake City",
  "SLE": "Salem",
  "SLK": "Saranac Lake",
  "SLN": "Salina",
  "SLP": "San Luis Potosi",
  "SLQ": "Sleetmore",
  "SLW": "Saltillo",
  "SLX": "Salt Cay",
  "SLY": "Salehard",
  "SLZ": "Sau Luiz",
  "SMF": "Sacramento",
  "SMI": "Samos",
  "SMK": "Saint Michael",
  "SML": "Stella Maris",
  "SMR": "Santa Marta",
  "SMS": "Sante Marie",
  "SMX": "Santa Maria",
  "SNA": "Santa Ana",
  "SNE": "Sao Nicolau",
  "SNN": "Shannon",
  "SNO": "Sakon Nakhon",
  "SNP": "Saint Paul Island",
  "SNW": "Thandwe",
  "SOC": "Solo City",
  "SOD": "Sorocaba",
  "SOF": "Sofia",
  "SOG": "Sognolal",
  "SOI": "South Molle Island",
  "SOJ": "Sorkjosen",
  "SON": "Espiritu Santo",
  "SOO": "Soderham",
  "SOP": "Southern Pines",
  "SOU": "South Hampton",
  "SOY": "Stronsay",
  "SPC": "Santa Cruz De La Palma",
  "SPI": "Springfield",
  "SPN": "Saipan",
  "SPS": "Wichita Falls",
  "SPU": "Split",
  "SQG": "Sintang",
  "SQH": "Son-La",
  "SQO": "Storuman",
  "SRE": "Sucre",
  "SRG": "Semarang",
  "SRQ": "Sarasota",
  "SRV": "Stony River",
  "SSA": "Salvadore",
  "SSG": "Malabo",
  "SSH": "Sharm El Sheikh",
  "SSR": "Sara",
  "STC": "Saint Cloud",
  "STG": "Saint George Island",
  "STL": "Saint Louis",
  "STM": "Santarem",
  "STR": "Stuttgart",
  "STS": "Santa Rosa",
  "STT": "St Thomas",
  "STW": "Stavropol",
  "STX": "Saint Croix",
  "SUB": "Surabaya",
  "SUF": "Lamezia-Terme",
  "SUJ": "Satu Mare",
  "SUL": "Sui",
  "SUN": "Sun Valley",
  "SUR": "Summer Beaver",
  "SUV": "Suva",
  "SUX": "Sioux City",
  "SVA": "Savoonga",
  "SVB": "Sambaua",
  "SVC": "Silver City",
  "SVD": "St Vincent",
  "SVG": "Stavanger",
  "SVJ": "Svolvaer",
  "SVL": "Savonlinna",
  "SVQ": "Sevilla",
  "SVS": "Stevens Village",
  "SVU": "Savusavu",
  "SVX": "Ekaterinburg",
  "SWA": "Shantou",
  "SWD": "Seward",
  "SWF": "Stewart Field/Newburgh",
  "SWG": "Satwag",
  "SXK": "Saumlaki",
  "SXL": "Sligo",
  "SXM": "St Maarten",
  "SXP": "Sheldon Point",
  "SXR": "Srinagar",
  "SYD": "Sydney",
  "SYM": "Simao",
  "SYO": "Shonai",
  "SYR": "Syracuse",
  "SYU": "Sue Island",
  "SYX": "Sanya",
  "SYY": "Stornoway",
  "SYZ": "Shiraz",
  "SZD": "Sheffield",
  "SZG": "Salzburg",
  "SZK": "Skukuza",
  "SZM": "Sesriem",
  "SZT": "S. Cristobal Del Casas",
  "SZX": "Shenzhen",
  "SZZ": "Szczecin",
  "TAB": "Tobago",
  "TAC": "Tacloban",
  "TAE": "Daegu",
  "TAH": "Tanna",
  "TAI": "Taiz",
  "TAL": "Tanana",
  "TAM": "Tampico",
  "TAO": "Qingdao",
  "TAP": "Tapachula",
  "TAR": "Taranto",
  "TAS": "Tashkent",
  "TAT": "Popraol/Tatry",
  "TBG": "Tabubil",
  "TBI": "The Bight",
  "TBJ": "Tabarka",
  "TBN": "Fort Leonard Wood",
  "TBO": "Tabora",
  "TBP": "Tumbes",
  "TBS": "Tbilisi",
  "TBT": "Tabatinga",
  "TBZ": "Tabriz",
  "TCA": "Tennant Creek",
  "TCB": "Treasure Cay",
  "TCG": "Tacheng",
  "TCH": "Tchibanga",
  "TCL": "Tuscaloosa",
  "TCO": "Tumaco",
  "TCP": "Taba",
  "TCQ": "Tacna",
  "TCT": "Takotna",
  "TDB": "Tetabedi",
  "TEE": "Tbessa",
  "TEH": "Tetlin",
  "TEK": "Tatitlek",
  "TER": "Terceira Island",
  "TET": "Tete",
  "TEU": "Te Anau",
  "TEX": "Telluride",
  "TEZ": "Tezpur",
  "TFF": "Tefe",
  "TFI": "Tufi",
  "TFN": "Tenerife",
  "TGD": "Podgoriea",
  "TGG": "Kuala Terengganu",
  "TGH": "Tongoa",
  "TGJ": "Tiga",
  "TGM": "Tirgu Mures",
  "TGN": "Traralgon",
  "TGO": "Tongliao",
  "TGU": "Tegucigalpa",
  "TGZ": "Tuxtla Gutierrez",
  "THE": "Teresina",
  "THG": "Thangool",
  "THL": "Tachilek",
  "THN": "Trollhattan",
  "THO": "Thorshofn",
  "THR": "Tehran",
  "THS": "Sukhotthai",
  "THU": "Pituffik",
  "TIA": "Tirana",
  "TID": "Tiaret",
  "TIE": "Tippi",
  "TIF": "Taif",
  "TIH": "Tikehau Atoll",
  "TIJ": "Tijuana",
  "TIM": "Tembagapura",
  "TIN": "Tindouf",
  "TIP": "Tripoli",
  "TIQ": "Tinian",
  "TIR": "Tirupati",
  "TIS": "Thursday Island",
  "TIU": "Timaru",
  "TIV": "Tivat",
  "TIY": "Tioljikja",
  "TIZ": "Tari",
  "TJA": "Tarija",
  "TJI": "Trujillo",
  "TJM": "Tyumen",
  "TJQ": "Tanjung Pandan",
  "TJS": "Tanjung Selor",
  "TKA": "Talkeetna",
  "TKB": "Tekadu",
  "TKE": "Tenakee Springs",
  "TKG": "Bandar Lampung",
  "TKJ": "Tok",
  "TKK": "Truk",
  "TKN": "Tokunoshima",
  "TKQ": "Kigoma",
  "TKS": "Tokushima",
  "TKU": "Turku",
  "TLC": "Toluco",
  "TLE": "Tulear",
  "TLH": "Tallahassee",
  "TLL": "Tallinn",
  "TLM": "Tlemcen",
  "TLN": "Toulon",
  "TLS": "Toulouse",
  "TLT": "Tuluksak",
  "TLV": "Tel Aviv",
  "TMC": "Tambolaka",
  "TMG": "Tomanggong",
  "TMH": "Tanahmerah",
  "TMJ": "Termez",
  "TMM": "Tamatave",
  "TMP": "Tampere",
  "TMR": "Tamanrasset",
  "TMS": "Sao Tome Is.",
  "TMT": "Trombetas",
  "TMU": "Tambor",
  "TMW": "Tamworth",
  "TMX": "Timimoun",
  "TNA": "Jinan",
  "TNC": "Tin City",
  "TND": "Trinidad",
  "TNG": "Tangier",
  "TNK": "Tununak",
  "TNN": "Tainan",
  "TNR": "Antaninvarivo",
  "TNX": "Stung Treng",
  "TOB": "Tobruk",
  "TOD": "Tioman",
  "TOE": "Tozeur",
  "TOF": "Tomsk",
  "TOG": "Togiak Village",
  "TOH": "Torres",
  "TOL": "Toledo",
  "TOM": "Tombouctou",
  "TOS": "Tromso",
  "TOU": "Touho",
  "TOV": "Tortola",
  "TOY": "Toyama",
  "TPA": "Tampa",
  "TPE": "Taipei",
  "TPP": "Tarapoto",
  "TPQ": "Tepic",
  "TPR": "Tom Price",
  "TPS": "Trapani",
  "TRA": "Taramajma",
  "TRC": "Torreon",
  "TRD": "Trondheim",
  "TRE": "Tiree",
  "TRG": "Tauranga",
  "TRI": "Bristol",
  "TRK": "Tarakan",
  "TRN": "Turin",
  "TRO": "Taree",
  "TRS": "Trieste",
  "TRV": "Thiruvananthapuram",
  "TRW": "Tarawa",
  "TRZ": "Tiruchirapally",
  "TSB": "Tsumeb",
  "TSE": "Astana",
  "TSJ": "Tsushima",
  "TSM": "Taos",
  "TSN": "Tianjn",
  "TSR": "Timosoara",
  "TST": "Trang",
  "TSV": "Townsville",
  "TTB": "Tortoli",
  "TTE": "Ternate",
  "TTJ": "Tottori",
  "TTN": "Trenton/Mercer",
  "TTQ": "Tortuquero",
  "TTS": "Tsaratanana",
  "TTT": "Taitung",
  "TTU": "Tetuan",
  "TUA": "Tulcan",
  "TUB": "Tubuai",
  "TUC": "Tucuman",
  "TUF": "Tours",
  "TUG": "Tuguegarao",
  "TUI": "Turaif",
  "TUJ": "Tum",
  "TUK": "Turbat",
  "TUL": "Tulsa",
  "TUN": "Tunis",
  "TUO": "Taupo",
  "TUP": "Tupelo",
  "TUR": "Tucurui",
  "TUS": "Tucson",
  "TUU": "Tabuk",
  "TUV": "Tucupita",
  "TVA": "Morafenobe",
  "TVC": "Traverse City",
  "TVF": "Thief River Falls",
  "TVU": "Taveuni",
  "TVY": "Dawe",
  "TWA": "Twin Hills",
  "TWB": "Toowoomba",
  "TWF": "Twin Falls",
  "TWU": "Tawau",
  "TXG": "Taichung",
  "TXK": "Texarkana",
  "TXM": "Teminabuan",
  "TXN": "Tunxi",
  "TYF": "Torsby",
  "TYN": "Taiyuan",
  "TYR": "Tyler",
  "TYS": "Knoxville",
  "TZN": "South Andros",
  "TZX": "Trabzon",
  "UAK": "Narsarsuaq",
  "UAS": "Samburu",
  "UBA": "Uberaba",
  "UBB": "Mabuiag Island",
  "UBJ": "Ube",
  "UBP": "Ubon Ratchathani",
  "UCA": "Utica",
  "UCT": "Ukhta",
  "UDI": "Uberlandia",
  "UDJ": "Uzhgorod",
  "UDR": "Udaipur",
  "UEL": "Quelimane",
  "UEO": "Kumejima",
  "UET": "Quetta",
  "UFA": "Ufa",
  "UGB": "Pilot Point",
  "UGC": "Urgench",
  "UGU": "Zugapa",
  "UIB": "Quibdo",
  "UIH": "Qui Nhon",
  "UIK": "Ust-Ilimsk",
  "UIN": "Quincy",
  "UIO": "Quito",
  "UIP": "Quimper",
  "UIT": "Jaluit Island",
  "UJE": "Ujae Island",
  "UKK": "Ust-Kamenogorsk",
  "ULA": "San Julian",
  "ULB": "Ulei",
  "ULD": "Ulundi",
  "ULI": "Ulithi",
  "ULN": "Ulaanbaatar",
  "ULP": "Quipi",
  "ULU": "Gulu",
  "ULY": "Uliastai",
  "UMD": "Uummannaq",
  "UME": "Umea",
  "UNG": "Kiunga",
  "UNK": "Unalakleet",
  "UNN": "Ranong",
  "UPG": "Ujung Pandang",
  "UPN": "Uruapan",
  "URA": "Uralsk",
  "URC": "Urumqi",
  "URG": "Uruguaiana",
  "URJ": "Uraj",
  "URO": "Rouen",
  "URT": "Surat Thani",
  "URU": "Uroubi",
  "URY": "Gurayat",
  "USH": "Ushuaia",
  "USK": "Usinsk",
  "USL": "Useless Loop",
  "USM": "Koh Samui",
  "USN": "Ulsan",
  "UTH": "Udon Thani",
  "UTK": "Utirik Island",
  "UTN": "Upington",
  "UTO": "Utopia Creek",
  "UTP": "Utapao",
  "UTT": "Umtata",
  "UUA": "Bugulma",
  "UUD": "Ulan-Ude",
  "UUS": "Yuzhno-Sakhalinsk",
  "UVE": "Ouvea",
  "UVF": "St. Lucia",
  "UVL": "Kharga",
  "UYL": "Nyala",
  "UYN": "Yulin",
  "UYU": "Uyuni",
  "VAA": "Vaasa",
  "VAG": "Varginha",
  "VAI": "Vanimo",
  "VAK": "Chevak",
  "VAN": "Van",
  "VAO": "Suavanao",
  "VAR": "Varna",
  "VAS": "Sivas",
  "VAT": "Vatomatry",
  "VAW": "Vardoe",
  "VBV": "Vanuabalavu",
  "VBY": "Visby",
  "VCD": "Victoria River Downs",
  "VCE": "Venice",
  "VCT": "Victoria",
  "VDA": "Ovda",
  "VDB": "Fagernes",
  "VDC": "Vitoria Da Conquista",
  "VDE": "Valverde",
  "VDM": "Viedma",
  "VDS": "Vadso",
  "VDZ": "Valdez",
  "VEE": "Venetie",
  "VEL": "Vernal",
  "VER": "Veracruz",
  "VEY": "Vestmannaeyjar",
  "VFA": "Victoria Falls",
  "VGO": "Vigo",
  "VHM": "Vilhelmina",
  "VIE": "Vienna",
  "VIG": "El Vigia",
  "VII": "Vinh City",
  "VIJ": "Virgin Gorda",
  "VIL": "Dakhla",
  "VIS": "Visalia",
  "VIT": "Vitoria",
  "VIV": "Vivigani",
  "VKG": "Rach Gia",
  "VKT": "Vorkuta",
  "VLC": "Valencia",
  "VLD": "Valdosta",
  "VLG": "Villa Gesell",
  "VLI": "Port Vila",
  "VLK": "Volgodonsk",
  "VLL": "Valladolid",
  "VLS": "Valesdir",
  "VLV": "Valera",
  "VME": "Villa Mercedes",
  "VMU": "Baimuru",
  "VNO": "Vilnius",
  "VNS": "Varanasi",
  "VNX": "Vilanculos",
  "VOG": "Volgograd",
  "VOH": "Vohemar",
  "VOZ": "Voronezh",
  "VPN": "Vopnafjordur",
  "VPS": "Fort Walton Beach",
  "VQS": "Vieques",
  "VRA": "Varadero",
  "VRK": "Varkaus",
  "VRN": "Verona",
  "VSA": "Villahermosa",
  "VSG": "Lugansk",
  "VST": "Vasteras",
  "VTB": "Vitebsk",
  "VTE": "Vientiane",
  "VTZ": "Vishakhapatnam",
  "VUP": "Valledupar",
  "VVB": "Mahanoro",
  "VVI": "Santa Cruz",
  "VVO": "Vladivostok",
  "VXC": "Lichinga",
  "VXE": "Sao Vicente",
  "VXO": "Vaxjo",
  "WAA": "Wales",
  "WAE": "Wadi Ad Dawasir",
  "WAG": "Wanganui",
  "WAI": "Antsohihy",
  "WAM": "Ambatondrazaka",
  "WAQ": "Antsalova",
  "WAS": "Washington Dc - All Airports",
  "WAT": "Waterford",
  "WAW": "Warsaw",
  "WBA": "Wahai",
  "WBB": "Stebbins",
  "WBQ": "Beaver",
  "WDG": "Enid",
  "WED": "Wedau",
  "WEH": "Weihai",
  "WEI": "Weipa",
  "WET": "Wagethe",
  "WFI": "Fianarantsoa",
  "WGA": "Wagga Wagga",
  "WGE": "Walgett",
  "WGP": "Waingapo",
  "WHF": "Wadi Halfa",
  "WHK": "Whakatane",
  "WIC": "Wick",
  "WIN": "Winton",
  "WJA": "Woja",
  "WJU": "Wonju",
  "WKA": "Wanaka",
  "WKJ": "Wakkanai",
  "WKK": "Aleknagik",
  "WLG": "Wellington",
  "WLH": "Walaha",
  "WLK": "Selawik",
  "WLS": "Wallis Island",
  "WMA": "Mandritsara",
  "WME": "Mount Keith",
  "WMH": "Mountain Home",
  "WMK": "Meyers Chuck",
  "WMN": "Maroantsetra",
  "WMO": "White Mountain",
  "WMP": "Mampikony",
  "WMR": "Mananara",
  "WMX": "Wamena",
  "WNA": "Napakiak",
  "WNN": "Wunnummin Lake",
  "WNP": "Naga",
  "WNR": "Windarra",
  "WNS": "Nawabshah",
  "WNZ": "Wenzhou",
  "WOT": "Wonan",
  "WPB": "Port Berge",
  "WRE": "Whangarei",
  "WRG": "Wrangell",
  "WRL": "Worland",
  "WRO": "Wroclaw",
  "WRY": "Westray",
  "WSN": "South Naknek",
  "WSR": "Wasior",
  "WST": "Westerly",
  "WSU": "Wasu",
  "WSX": "Westsound",
  "WSZ": "Westport",
  "WTA": "Tambohorano",
  "WTE": "Wotje Island",
  "WTK": "Noatak",
  "WTL": "Tuntutuliak",
  "WTO": "Wotho Island",
  "WTS": "Tsiroanomandidy",
  "WUD": "Wudinna",
  "WUG": "Wau",
  "WUH": "Wuhan",
  "WUN": "Wiluna",
  "WUS": "Wuyishan",
  "WVB": "Walvis Bay",
  "WVK": "Manakara",
  "WVN": "Wilhelmshaven",
  "WWK": "Wewak",
  "WWP": "Whale Pass",
  "WWT": "Newtok",
  "WXN": "Wanxian",
  "WYA": "Whyalla",
  "WYN": "Wyndham",
  "XAD": "Churchill",
  "XAK": "Herning",
  "XAP": "Chapeco",
  "XAW": "Capreol",
  "XAZ": "Campbellton",
  "XBE": "Bearskin Lake",
  "XBR": "Brockville",
  "XCH": "Christmas Island",
  "XCI": "Chambord",
  "XCM": "Chatham",
  "XDD": "Gaspe",
  "XDH": "Jasper",
  "XDL": "Chandler",
  "XDM": "Drummondville",
  "XDP": "Moncton",
  "XDU": "Hervey",
  "XDV": "Prince George",
  "XDW": "Prince Rupert",
  "XDX": "Sarnia",
  "XDY": "Sudbury",
  "XDZ": "The Pas",
  "XEC": "Windsor",
  "XEE": "Lac Edouard",
  "XEH": "Ladysmith",
  "XEJ": "Langford",
  "XEK": "Melville",
  "XEL": "New Carlisle",
  "XEM": "New Richmond",
  "XER": "Strasbourg",
  "XEY": "Miramichi",
  "XFC": "Fredericton Junction",
  "XFE": "Parent",
  "XFG": "Perce",
  "XFK": "Senneterre",
  "XFL": "Shawinigan",
  "XFM": "Shawnigan",
  "XFN": "Xiangfan",
  "XFQ": "Weymont",
  "XFV": "Brantford",
  "XFW": "Finkenwerder",
  "XGJ": "Cobourg",
  "XGK": "Coteau",
  "XGR": "Kangiqsualujjuaq",
  "XGY": "Grimsby",
  "XHH": "Boulder",
  "XHM": "Georgetown",
  "XHS": "Chemainus",
  "XIA": "Guelph",
  "XIB": "Ingersoll",
  "XIC": "Xichang",
  "XID": "Maxville",
  "XIF": "Napanee",
  "XIL": "Xilinhot",
  "XIM": "Saint Hyacinthe",
  "XIO": "St Marys",
  "XIP": "Woodstock",
  "XIY": "Xi An",
  "XJL": "Joliette",
  "XJQ": "Jonquiere",
  "XKH": "Xieng Khouang",
  "XKS": "Kasabonika",
  "XKV": "Sackville",
  "XLB": "Lac Brochet",
  "XLY": "Aldershot",
  "XLZ": "Truro",
  "XMH": "Manihi",
  "XMN": "Xiamen",
  "XMS": "Macas",
  "XMY": "Yam Island",
  "XNN": "Xining",
  "XPB": "Parksville",
  "XPK": "Pukatawagan",
  "XPN": "Brampton",
  "XPX": "Pointe-Aux-Trembles",
  "XQU": "Qualicum",
  "XRP": "Riviere-A-Pierre",
  "XRY": "Jerez De La Frontere",
  "XSC": "South Caicos",
  "XSI": "South Indian Lake",
  "XTG": "Thargomindah",
  "XTL": "Tadoule Lake",
  "XTY": "Strathroy",
  "XUZ": "Xuzhou",
  "XVS": "Valenciennes",
  "XWA": "Watford",
  "XWY": "Wyoming",
  "XYA": "Yandina",
  "XZB": "Casselman",
  "XZC": "Glencoe",
  "YAA": "Anahim Lake",
  "YAB": "Arctic Bay",
  "YAC": "Cat Lake",
  "YAG": "Fort Frances",
  "YAI": "Chillan",
  "YAK": "Yakutat",
  "YAM": "Sault Ste-Marie",
  "YAO": "Yaounde",
  "YAP": "Yap",
  "YAT": "Attawapiskat",
  "YAX": "Angling Lake",
  "YAY": "St Anthony",
  "YAZ": "Tofino",
  "YBB": "Kugaaruk",
  "YBC": "Baie Comeau",
  "YBE": "Uranium City",
  "YBG": "Bagotville",
  "YBI": "Black Tickle",
  "YBK": "Baker Lake",
  "YBL": "Campbell River",
  "YBP": "Yibin",
  "YBR": "Brandon",
  "YBS": "Opapamiska Lake",
  "YBT": "Brochet",
  "YBV": "Berens River",
  "YBX": "Blanc Sablon",
  "YCA": "Courtenay",
  "YCB": "Cambridge Bay",
  "YCC": "Cornwall",
  "YCG": "Castlegar",
  "YCK": "Colville Lake",
  "YCM": "St Catharines",
  "YCO": "Kugluktuk/Coppermine",
  "YCR": "Cross Lake",
  "YCS": "Chesterfield Inlet",
  "YCY": "Clyde River",
  "YDA": "Dawson City",
  "YDF": "Deer Lake",
  "YDI": "Davis Inlet",
  "YDN": "Dauphin",
  "YDP": "Nain",
  "YDQ": "Dawson Creek",
  "YEG": "Edmonton",
  "YEK": "Arviat",
  "YER": "Fort Severn",
  "YEV": "Inuvik",
  "YFA": "Fort Albany",
  "YFB": "Iqaluit",
  "YFC": "Fredericton",
  "YFH": "Fort Hope",
  "YFJ": "Snare Lake",
  "YFO": "Flin Flon",
  "YFS": "Fort Simpson",
  "YFX": "Fox Harbour/st Lewis",
  "YGB": "Gillies Bay",
  "YGH": "Fort Good Hope",
  "YGJ": "Yonago",
  "YGL": "La Grande",
  "YGO": "Gods Narrows",
  "YGR": "Iles De La Madeleine",
  "YGT": "Igloolik",
  "YGV": "Havre St Pierre",
  "YGW": "Kuujjuarapik",
  "YGX": "Gillam",
  "YGZ": "Grise Fiord",
  "YHA": "Port Hope Simpson",
  "YHB": "Hudson Bay",
  "YHD": "Dryden",
  "YHG": "Charlottetown",
  "YHI": "Holman",
  "YHK": "Gjoa Haven",
  "YHM": "Hamilton",
  "YHO": "Hopedale",
  "YHP": "Poplar Hill",
  "YHR": "Chevery",
  "YHY": "Hay River",
  "YHZ": "Halifax",
  "YIF": "Pakuashipi",
  "YIH": "Yichang",
  "YIK": "Ivujivik",
  "YIN": "Yining",
  "YIO": "Pond Inlet",
  "YIV": "Island Lake/Garden Hill",
  "YIW": "Yiwu",
  "YJT": "Stephenville",
  "YKA": "Kamloops",
  "YKF": "Kitchener",
  "YKG": "Kangirsuk",
  "YKL": "Schefferville",
  "YKM": "Yakima",
  "YKQ": "Waskaganish",
  "YKS": "Yakutsk",
  "YKT": "Klemtu",
  "YKU": "Chisasibi",
  "YLC": "Kimmirut/Lake Harbour",
  "YLD": "Chapleau",
  "YLE": "Wha Ti/Lac La Martre",
  "YLH": "Lansdowne House",
  "YLL": "Lloydminister",
  "YLQ": "La Tuque",
  "YLR": "Leaf Rapids",
  "YLW": "Kelowna",
  "YMM": "Fort Mcmurray",
  "YMO": "Moosonee",
  "YMT": "Chibougamau",
  "YNA": "Natashquan",
  "YNB": "Yanbu",
  "YNC": "Wemindji",
  "YNE": "Norway House",
  "YNG": "Youngstown",
  "YNJ": "Yanji",
  "YNL": "Points North Landing",
  "YNO": "North Spirit Lake",
  "YNS": "Nemiscau",
  "YNT": "Yantai",
  "YNZ": "Yancheng",
  "YOC": "Old Crow",
  "YOG": "Ogoki",
  "YOH": "Oxford House",
  "YOJ": "High Level",
  "YOO": "Oshawa",
  "YOP": "Rainbow Lake",
  "YOW": "Ottawa",
  "YPA": "Prince Albert",
  "YPB": "Port Alberni",
  "YPC": "Paulatuk",
  "YPE": "Peace River",
  "YPF": "Esquimalt",
  "YPH": "Inukjuak",
  "YPJ": "Aupaluk",
  "YPL": "Pickle Lake",
  "YPM": "Pikangikum",
  "YPN": "Port Meiner",
  "YPO": "Peawanuck",
  "YPW": "Powell River",
  "YPX": "Povungnituk",
  "YPY": "Fort Chipewyan",
  "YPZ": "Burns Lake",
  "YQB": "Quebec",
  "YQC": "Quaqtaq",
  "YQI": "Yarmouth",
  "YQK": "Kenora",
  "YQL": "Lethbridge",
  "YQN": "Nakina",
  "YQQ": "Comox",
  "YQR": "Regina",
  "YQT": "Thunder Bay",
  "YQU": "Grande Prairie",
  "YQX": "Gander",
  "YQZ": "Quesnel",
  "YRA": "Rae Lakes",
  "YRB": "Resolute",
  "YRF": "Cartwright",
  "YRG": "Rigolet",
  "YRJ": "Roberval",
  "YRL": "Red Lake",
  "YRS": "Red Sucker Lake",
  "YRT": "Rankin Inlet",
  "YSF": "Stony Rapids",
  "YSG": "Lutselke/snowdrift",
  "YSH": "Smith Falls",
  "YSJ": "Saint John",
  "YSK": "Sanikiluaq",
  "YSL": "Saint Leonard",
  "YSO": "Postville",
  "YSR": "Nanisivik",
  "YST": "Ste Therese Point",
  "YSY": "Sachs Harbour",
  "YTA": "Pembroke",
  "YTD": "Thicket Portage",
  "YTE": "Cape Dorset",
  "YTF": "Alma",
  "YTH": "Thompson",
  "YTL": "Big Trout",
  "YTQ": "Tasiujuaq",
  "YTS": "Timmins",
  "YUB": "Tuktoyaktuk",
  "YUD": "Umiujag",
  "YUL": "Montreal",
  "YUM": "Yuma",
  "YUT": "Repulse Bay",
  "YUX": "Hall Beach",
  "YUY": "Noranda/Rouyn",
  "YVB": "Bonaventure",
  "YVC": "La Ronge",
  "YVM": "Qikiqtarjuaq",
  "YVP": "Kuujjuaq",
  "YVQ": "Norman Wells",
  "YVR": "Vancouver",
  "YWB": "Kangiqsujuaq",
  "YWG": "Winnipeg",
  "YWJ": "Deline",
  "YWK": "Wabush",
  "YWL": "Williams Lake",
  "YWM": "Williams Harbour",
  "YWP": "Webequie",
  "YXC": "Cranbrook",
  "YXE": "Saskatoon",
  "YXH": "Medicine Hat",
  "YXJ": "Fort St John",
  "YXK": "Rimouski",
  "YXL": "Sioux Lookout",
  "YXN": "Whale Cove",
  "YXP": "Pangnirtung",
  "YXT": "Terrace",
  "YXX": "Abbotsford",
  "YXY": "Whitehorse",
  "YYB": "North Bay",
  "YYC": "Calgary",
  "YYD": "Smithers",
  "YYE": "Fort Nelson",
  "YYF": "Penticton",
  "YYH": "Taloyoak",
  "YYR": "Goose Bay",
  "YYT": "Saint Johns",
  "YYU": "Kapuskasing",
  "YYY": "Mont Joli",
  "YYZ": "Toronto",
  "YZF": "Yellowknife",
  "YZG": "Salluit",
  "YZS": "Coral Harbour",
  "YZT": "Port Hardy",
  "YZV": "Sept-Iles",
  "ZAC": "York Landing",
  "ZAD": "Zadar",
  "ZAG": "Zagreb",
  "ZAH": "Zahedan",
  "ZAL": "Valdivia",
  "ZAM": "Zamboanga",
  "ZAQ": "Nuremberg",
  "ZAT": "Zhaotong",
  "ZAZ": "Zaragoza",
  "ZBF": "Bathhurst",
  "ZBJ": "Fredericia",
  "ZBQ": "Odense",
  "ZBR": "Chah-Bahar",
  "ZBV": "Beaver Creek",
  "ZBY": "Sayaboury",
  "ZCO": "Temuco",
  "ZDH": "Basel/Mulhouse Railway Station",
  "ZEG": "Senggo",
  "ZEL": "Bella Bella",
  "ZEM": "East Main",
  "ZFD": "Fond Du Lac",
  "ZFN": "Tulita/Fort Norman",
  "ZGC": "Lanzhou",
  "ZGI": "Gods River",
  "ZGS": "Gethsemani",
  "ZGU": "Gaua",
  "ZHA": "Zhanjiang",
  "ZHQ": "Halberstadt",
  "ZID": "Aarhus",
  "ZIH": "Zihuatanejo/Ixtapa",
  "ZJN": "Swan River",
  "ZKB": "Kasaba Bay",
  "ZKE": "Kaschechewan",
  "ZKG": "Kegaska",
  "ZLN": "Le Mans",
  "ZLT": "La Tabatiere",
  "ZNA": "Nanaimo",
  "ZNE": "Newman",
  "ZNZ": "Zanzibar",
  "ZPB": "Sachigo Lake",
  "ZQN": "Queenstown",
  "ZRF": "Rockford",
  "ZRH": "Zurich",
  "ZRI": "Servi",
  "ZRJ": "Round Lake",
  "ZRM": "Sarmi",
  "ZSE": "St. Pierre De La Reunion",
  "ZSJ": "Sandy Lake",
  "ZTB": "Tete-A-La Baleine",
  "ZTH": "Zakinthos Island",
  "ZTM": "Shamattawa",
  "ZUH": "Zhuhai",
  "ZUM": "Churchill Falls",
  "ZVA": "Miandrivazo",
  "ZVK": "Savannakhet",
  "ZWL": "Wollaston Lake",
  "ZXM": "Rognan",
  "ZYL": "Sylhet",
  "ZZU": "Mzuzu"
};

